#pragma once

#include <Arduino.h>

// UI-Erweiterungen fuer 2.1.0. Die bestehende 1.0.1-Oberflaeche bleibt die Basis;
// neue Module werden mit denselben Karten, Buttons, Hardware-Icons und Sprachregeln
// in die vorhandenen Bereiche Einstellungen und Geraet eingesetzt.
static const char WEB_UI_V2[] PROGMEM = R"HTML(
<style>
.v2Full{grid-column:1/-1}.v2StatusLine{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:12px}.v2Dot{width:9px;height:9px;border-radius:50%;background:var(--muted);display:inline-block}.v2Dot.ok{background:var(--ok)}.v2Dot.bad{background:var(--danger)}
.v2SoundCounters{margin-top:12px}.v2TrackBox{margin-top:14px;border-top:1px solid var(--line);padding-top:12px}.v2TrackBox summary{cursor:pointer;font-weight:600;margin-bottom:10px}.v2TrackWrap{max-height:340px;overflow:auto;border:1px solid var(--line);border-radius:9px}.v2TrackTable{width:100%;border-collapse:collapse}.v2TrackTable th,.v2TrackTable td{padding:7px 9px;border-bottom:1px solid var(--line);text-align:left}.v2TrackTable th:first-child,.v2TrackTable td:first-child{width:70px;text-align:center}.v2TrackTable input{width:100%;min-width:130px}
.v2WdWrap{overflow:auto}.v2WdTable{width:100%;border-collapse:collapse;min-width:720px}.v2WdTable th,.v2WdTable td{padding:7px 9px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap}.v2WdTable td.ok{color:var(--ok);font-weight:600}.v2WdTable td.warn{color:var(--accent);font-weight:600}.v2WdTable td.off{color:var(--muted);font-weight:600}.v2WdTable td.bad{color:var(--danger);font-weight:600}.v2WdTable td.num{font-variant-numeric:tabular-nums;text-align:right}.v2WdTable th.num{text-align:right}
.v2OtaRow{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.v2OtaRow input[type=file]{max-width:100%}.v2Hint{font-size:.8rem;color:var(--muted);line-height:1.45;margin-top:9px}.v2Result{font-size:.8rem;color:var(--muted);margin-top:8px}.v2Result.ok{color:var(--ok)}.v2Result.bad{color:var(--danger)}
#soundSave,#soundTest,#trackListSave,#otaInstall{display:inline-flex;align-items:center;justify-content:center;position:relative;min-height:40px}#soundSave,#trackListSave,#otaInstall{background:var(--accent);border-color:var(--accent);color:#fff}
.v2Check{display:inline-flex;align-items:center;gap:7px}.v2Check input{width:18px;height:18px}.v2Range{display:grid;grid-template-columns:1fr 82px;gap:8px;align-items:center}.v2Range input[type=range]{width:100%;padding:0}
@media(max-width:520px){.v2Range{grid-template-columns:1fr 72px}.v2TrackWrap{max-height:280px}}
</style>
<script>
(function(){'use strict';
const $=id=>document.getElementById(id);
let soundSettingsLoaded=false;
const T={
 de:{
  sound_title:'DY-SV17F Soundmodul',sound_hw_ok:'Hardware erkannt',sound_hw_missing:'Hardware nicht erkannt',sound_hw_probe:'Hardwareprüfung läuft',sound_enabled:'Sound bei Unterbrechung',sound_volume:'Lautstärke',sound_track:'Track',sound_save:'Sound speichern',sound_test:'Testton',sound_sent:'Befehle gesendet',sound_done:'Erfolgreich abgeschlossen',sound_failed:'Fehlgeschlagen',sound_timeouts:'Timeouts',sound_responses:'Gültige Antworten',sound_errors:'UART/Protokollfehler',sound_help:'Das Soundmodul ist optional. Ein Track wird erst abgespielt, nachdem die Unterbrechung sicher gespeichert wurde. Ohne bestätigte DY-SV17F-Hardware bleibt der Zähler für gesendete Töne unverändert.',
  tracks_title:'Trackliste / Tonbelegung',tracks_help:'Hier steht, welcher nummerierte Track welcher Ton ist. Die Audiodateien selbst bleiben einmalig auf dem DY-SV17F; gespeichert werden hier nur die Beschreibungen.',tracks_num:'Track',tracks_name:'Beschreibung',tracks_save:'Trackliste speichern',tracks_saved:'Trackliste gespeichert.',tracks_error:'Trackliste konnte nicht gespeichert werden.',
  wd_title:'Watchdog / Moduldiagnose',wd_hw:'ESP32 Hardware-Watchdog aktiv',wd_module:'Modul',wd_status:'Status',wd_detail:'Detail',wd_age:'Letztes Lebenszeichen',wd_last:'Letzter Lauf',wd_max:'Maximum',wd_slow:'Langsam',wd_errors:'Fehler',wd_ok:'Bereit',wd_error:'FEHLER',wd_disabled:'Deaktiviert',wd_initializing:'Initialisierung',wd_busy:'Beschäftigt',wd_not_detected:'Nicht erkannt',wd_degraded:'Eingeschränkt',wd_timeout:'Timeout',wd_now:'jetzt',wd_help:'Rot bedeutet: Modulpfad liefert kein gültiges Lebenszeichen mehr. Ein langsamer Webrequest wird separat gezählt und ist nicht automatisch ein Watchdog-Fehler.',
  ota_title:'OTA Firmware',ota_choose:'Firmware-BIN auswählen',ota_install:'Firmware installieren',ota_none:'Bitte zuerst eine .bin-Datei auswählen.',ota_running:'Firmware wird übertragen …',ota_ok:'Update erfolgreich. Der ESP32 startet neu.',ota_error:'OTA-Update fehlgeschlagen.',ota_help:'Nur eine für diesen ESP32 erzeugte Firmware-BIN verwenden. WLAN-Zugangsdaten werden ab 2.0.0 persistent gespeichert und nicht mehr aus der OTA-Datei überschrieben.',
  saved:'Gespeichert.',save_error:'Speichern fehlgeschlagen.',test_started:'Testton gestartet.',test_missing:'Soundhardware ist nicht erkannt.',sound_icon:'DY-SV17F Soundmodul'
 },
 en:{
  sound_title:'DY-SV17F sound module',sound_hw_ok:'Hardware detected',sound_hw_missing:'Hardware not detected',sound_hw_probe:'Checking hardware',sound_enabled:'Sound on interruption',sound_volume:'Volume',sound_track:'Track',sound_save:'Save sound',sound_test:'Test sound',sound_sent:'Commands sent',sound_done:'Completed successfully',sound_failed:'Failed',sound_timeouts:'Timeouts',sound_responses:'Valid responses',sound_errors:'UART/protocol errors',sound_help:'The sound module is optional. A track is triggered only after the interruption has been stored safely. Without confirmed DY-SV17F hardware the sent-sound counter does not increase.',
  tracks_title:'Track list / sound assignment',tracks_help:'Use this list to record which numbered track contains which sound. Audio files stay on the DY-SV17F; only the descriptions are stored here.',tracks_num:'Track',tracks_name:'Description',tracks_save:'Save track list',tracks_saved:'Track list saved.',tracks_error:'Track list could not be saved.',
  wd_title:'Watchdog / module diagnostics',wd_hw:'ESP32 hardware watchdog active',wd_module:'Module',wd_status:'Status',wd_detail:'Detail',wd_age:'Last heartbeat',wd_last:'Last run',wd_max:'Maximum',wd_slow:'Slow',wd_errors:'Errors',wd_ok:'Ready',wd_error:'ERROR',wd_disabled:'Disabled',wd_initializing:'Initializing',wd_busy:'Busy',wd_not_detected:'Not detected',wd_degraded:'Degraded',wd_timeout:'Timeout',wd_now:'now',wd_help:'Red means that a module path no longer provides a valid heartbeat. A slow web request is counted separately and is not automatically a watchdog error.',
  ota_title:'OTA firmware',ota_choose:'Select firmware BIN',ota_install:'Install firmware',ota_none:'Please select a .bin file first.',ota_running:'Uploading firmware …',ota_ok:'Update successful. The ESP32 is restarting.',ota_error:'OTA update failed.',ota_help:'Use only firmware built for this ESP32. From 2.0.0 onward Wi-Fi credentials are stored persistently and are no longer replaced by the OTA file.',
  saved:'Saved.',save_error:'Save failed.',test_started:'Test sound started.',test_missing:'Sound hardware is not detected.',sound_icon:'DY-SV17F sound module'
 },
 swg:{
  sound_title:'DY-SV17F Krachmacher',sound_hw_ok:'Hardware gfunda',sound_hw_missing:'Hardware ned gfunda',sound_hw_probe:'I guck nach dr Hardware',sound_enabled:'Bei dr Unterbrechung Krach macha',sound_volume:'Lautstärk',sound_track:'Track',sound_save:'Sound speichera',sound_test:'Ton ausprobiera',sound_sent:'Befehle nausgschickt',sound_done:'Sauber fertig',sound_failed:'Daneba ganga',sound_timeouts:'Timeouts',sound_responses:'Gültige Antworta',sound_errors:'UART-/Protokollfehler',sound_help:'Dr Krachmacher isch optional. Dr Ton kommt erscht dran, wenn d Unterbrechung sicher gspeichert isch. Wenn koi DY-SV17F wirklich antwortet, wird au koi Ton als gsendet gezählt.',
  tracks_title:'Tracklischt / welcher Ton isch wo',tracks_help:'Do kasch neischreiba, welcher Track welchen Krach macht. D Audiodateia bleibet einmal auf em DY-SV17F; do speichere mer bloß d Beschreibung.',tracks_num:'Track',tracks_name:'Beschreibung',tracks_save:'Tracklischt speichera',tracks_saved:'Tracklischt isch gspeichert.',tracks_error:'Tracklischt hot sich ned speichera lassa.',
  wd_title:'Watchdog / Moduldiagnose',wd_hw:'ESP32 Hardware-Watchdog isch aktiv',wd_module:'Modul',wd_status:'Status',wd_detail:'Detail',wd_age:'Letschtes Lebenszeicha',wd_last:'Letschter Lauf',wd_max:'Maximum',wd_slow:'Langsam',wd_errors:'Fehler',wd_ok:'Bereit',wd_error:'FEHLER',wd_disabled:'Ausgschaltet',wd_initializing:'Startet grad',wd_busy:'Schafft grad',wd_not_detected:'Ned gfunda',wd_degraded:'Eingeschränkt',wd_timeout:'Timeout',wd_now:'grad eben',wd_help:'Rot heißt: dr Modulpfad liefert koi gültigs Lebenszeicha meh. En langsamer Webrequest wird extra gezählt und isch ned automatisch en Watchdog-Fehler.',
  ota_title:'OTA Firmware',ota_choose:'Firmware-BIN aussucha',ota_install:'Firmware installiera',ota_none:'Such erscht a .bin-Datei aus.',ota_running:'Firmware wird rübergschoba …',ota_ok:'Update hot klappt. Dr ESP32 startet neu.',ota_error:'OTA-Update hot ned klappt.',ota_help:'Bloß a Firmware-BIN für genau den ESP32 neh. Ab 2.0.0 bleibet d WLAN-Zugangsdada dauerhaft gspeichert und werdet von dr OTA-Datei nemme plattgmacht.',
  saved:'Gspeichert.',save_error:'Speichera hot ned klappt.',test_started:'Testton lauft.',test_missing:'Soundhardware isch ned gfunda.',sound_icon:'DY-SV17F Krachmacher'
 }
};
function lang(){return localStorage.getItem('uic-lang')||'de'}function tr(k){let l=lang();return(T[l]&&T[l][k])||T.de[k]||k}
function fmtUs(v){v=Number(v||0);if(!v)return'-';if(v>=1000000)return(v/1000000).toFixed(2)+' s';if(v>=1000)return(v/1000).toFixed(v>=10000?0:1)+' ms';return v+' µs'}
function fmtAge(v){v=Number(v||0);if(v>4000000000)return'-';if(v<1500)return tr('wd_now');if(v<60000)return Math.round(v/1000)+' s';return Math.round(v/60000)+' min'}
function statusText(state){let key={ready:'wd_ok',error:'wd_error',disabled:'wd_disabled',initializing:'wd_initializing',busy:'wd_busy',not_detected:'wd_not_detected',degraded:'wd_degraded',timeout:'wd_timeout'}[state]||'wd_error';return tr(key)}
function statusClass(state){if(state==='ready'||state==='busy')return'ok';if(state==='disabled'||state==='not_detected')return'off';if(state==='initializing'||state==='degraded')return'warn';return'bad'}
function ensure(){let s=document.querySelector('#settings .settingsGrid');if(s&&!$('soundCard')){let c=document.createElement('div');c.id='soundCard';c.className='settingsBox';c.innerHTML=`<h3><span class="hwIcon unavailable" id="headSound" aria-hidden="true">🔊</span>${tr('sound_title')}</h3><div class="v2StatusLine"><span id="soundDot" class="v2Dot"></span><b id="soundHwText">${tr('sound_hw_probe')}</b></div><div class="settingsRow"><label>${tr('sound_enabled')}</label><label class="v2Check"><input id="soundEnabled" type="checkbox"><span>${tr('sound_enabled')}</span></label></div><div class="settingsRow"><label>${tr('sound_volume')}</label><div class="v2Range"><input id="soundVolume" type="range" min="0" max="30" step="1"><input id="soundVolumeN" type="number" min="0" max="30"></div></div><div class="settingsRow"><label>${tr('sound_track')}</label><input id="soundTrack" type="number" min="1" max="65535"></div><div class="actions"><button id="soundSave">${tr('sound_save')}</button><button id="soundTest">${tr('sound_test')}</button></div><div id="soundResult" class="v2Result"></div><div class="kvGrid v2SoundCounters"><span>${tr('sound_sent')}</span><strong id="soundSent">-</strong><span>${tr('sound_done')}</span><strong id="soundDone">-</strong><span>${tr('sound_failed')}</span><strong id="soundFailed">-</strong><span>${tr('sound_timeouts')}</span><strong id="soundTimeouts">-</strong><span>${tr('sound_responses')}</span><strong id="soundResponses">-</strong><span>${tr('sound_errors')}</span><strong id="soundErrors">-</strong></div><details class="v2TrackBox"><summary>${tr('tracks_title')}</summary><p class="v2Hint">${tr('tracks_help')}</p><div class="v2TrackWrap"><table class="v2TrackTable"><thead><tr><th>${tr('tracks_num')}</th><th>${tr('tracks_name')}</th></tr></thead><tbody id="trackRows"></tbody></table></div><div class="actions"><button id="trackListSave">${tr('tracks_save')}</button></div><div id="trackResult" class="v2Result"></div></details><p class="infoHelp">${tr('sound_help')}</p>`;s.appendChild(c);wireSound()}
let d=document.querySelector('#device .infoGrid');if(d&&!$('watchdogCard')){let w=document.createElement('div');w.id='watchdogCard';w.className='infoBox v2Full';w.innerHTML=`<h3>🛡️ ${tr('wd_title')}</h3><div class="v2StatusLine"><span class="v2Dot ok"></span><b>${tr('wd_hw')}</b></div><div class="v2WdWrap"><table class="v2WdTable"><thead><tr><th>${tr('wd_module')}</th><th>${tr('wd_status')}</th><th>${tr('wd_detail')}</th><th class="num">${tr('wd_age')}</th><th class="num">${tr('wd_last')}</th><th class="num">${tr('wd_max')}</th><th class="num">${tr('wd_slow')}</th><th class="num">${tr('wd_errors')}</th></tr></thead><tbody id="watchdogRows"></tbody></table></div><p class="infoHelp">${tr('wd_help')}</p>`;d.appendChild(w)}
if(d&&!$('otaCard')){let o=document.createElement('div');o.id='otaCard';o.className='infoBox v2Full';o.innerHTML=`<h3>⬆️ ${tr('ota_title')}</h3><div class="v2OtaRow"><input id="otaFile" type="file" accept=".bin,application/octet-stream" aria-label="${tr('ota_choose')}"><button id="otaInstall">${tr('ota_install')}</button></div><div id="otaResult" class="v2Result"></div><p class="infoHelp">${tr('ota_help')}</p>`;d.appendChild(o);$('otaInstall').onclick=installOta}}
function wireSound(){let r=$('soundVolume'),n=$('soundVolumeN');if(r&&n){r.oninput=()=>n.value=r.value;n.oninput=()=>r.value=n.value}$('soundSave').onclick=saveSound;$('soundTest').onclick=testSound;$('trackListSave').onclick=saveTracks;loadTracks()}
function setResult(id,text,good){let e=$(id);if(!e)return;e.textContent=text;e.className='v2Result '+(good?'ok':'bad')}
async function saveSound(){let p=new URLSearchParams();p.set('enabled',$('soundEnabled').checked?'1':'0');p.set('volume',$('soundVolume').value);p.set('track',$('soundTrack').value);try{let r=await fetch('/api/sound-settings',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p.toString()});if(!r.ok)throw 0;setResult('soundResult',tr('saved'),true)}catch(e){setResult('soundResult',tr('save_error'),false)}}
async function testSound(){try{let r=await fetch('/api/sound-test',{method:'POST'});if(!r.ok)throw 0;setResult('soundResult',tr('test_started'),true)}catch(e){setResult('soundResult',tr('test_missing'),false)}}
async function loadTracks(){try{let r=await fetch('/api/tracks',{cache:'no-store'}),d=await r.json();if(!d.ok)return;let m={};(d.tracks||[]).forEach(x=>m[Number(x.id)]=x.name||'');let b=$('trackRows');if(!b)return;b.innerHTML='';for(let i=1;i<=100;i++){let trr=document.createElement('tr');trr.innerHTML='<td>'+i+'</td><td><input type="text" maxlength="80" data-track="'+i+'"></td>';trr.querySelector('input').value=m[i]||'';b.appendChild(trr)}}catch(e){}}
async function saveTracks(){let lines=[];document.querySelectorAll('#trackRows input[data-track]').forEach(i=>{let v=i.value.trim();if(v)lines.push(i.dataset.track+'|'+v.replace(/[\r\n|]+/g,' '))});try{let r=await fetch('/api/tracks',{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:lines.join('\n')});if(!r.ok)throw 0;setResult('trackResult',tr('tracks_saved'),true)}catch(e){setResult('trackResult',tr('tracks_error'),false)}}
function applyStatus(d){ensure();let s=d.sound||{},head=$('headSound'),dot=$('soundDot'),txt=$('soundHwText');if(head){head.classList.toggle('available',!!s.present);head.classList.toggle('unavailable',!s.present);head.title=tr('sound_icon')}if(dot){dot.className='v2Dot '+(s.present?'ok':(s.hardwareState==='probing'?'':'bad'))}if(txt)txt.textContent=s.present?tr('sound_hw_ok'):(s.hardwareState==='probing'?tr('sound_hw_probe'):tr('sound_hw_missing'));if(!soundSettingsLoaded){if($('soundEnabled'))$('soundEnabled').checked=!!s.enabled;if($('soundVolume'))$('soundVolume').value=s.volume||20;if($('soundVolumeN'))$('soundVolumeN').value=s.volume||20;if($('soundTrack'))$('soundTrack').value=s.track||1;soundSettingsLoaded=true}if($('soundSent'))$('soundSent').textContent=s.sent||0;if($('soundDone'))$('soundDone').textContent=s.completed||0;if($('soundFailed'))$('soundFailed').textContent=s.failed||0;if($('soundTimeouts'))$('soundTimeouts').textContent=s.timeouts||0;if($('soundResponses'))$('soundResponses').textContent=s.responses||0;if($('soundErrors'))$('soundErrors').textContent=s.errors||0;let body=$('watchdogRows');if(body){body.innerHTML='';(d.modules||[]).forEach(m=>{let st=m.state||'error',row=document.createElement('tr');row.innerHTML='<td>'+m.name+'</td><td class="'+statusClass(st)+'">'+statusText(st)+'</td><td>'+(m.detail||'-')+'</td><td class="num">'+fmtAge(m.ageMs)+'</td><td class="num">'+fmtUs(m.lastUs)+'</td><td class="num">'+fmtUs(m.maxUs)+'</td><td class="num">'+Number(m.slow||0)+'</td><td class="num">'+Number(m.errors||0)+'</td>';body.appendChild(row)})}}
async function installOta(){let f=$('otaFile').files[0];if(!f){setResult('otaResult',tr('ota_none'),false);return}let b=$('otaInstall');b.disabled=true;setResult('otaResult',tr('ota_running'),true);try{let fd=new FormData();fd.append('firmware',f,f.name);let r=await fetch('/api/ota',{method:'POST',body:fd});if(!r.ok)throw 0;setResult('otaResult',tr('ota_ok'),true)}catch(e){setResult('otaResult',tr('ota_error'),false);b.disabled=false}}
function init(){ensure();document.addEventListener('uic:status',e=>applyStatus(e.detail||{}));let ls=$('languageSelect');if(ls)ls.addEventListener('change',()=>{soundSettingsLoaded=false;setTimeout(()=>{let c=$('soundCard'),w=$('watchdogCard'),o=$('otaCard');if(c)c.remove();if(w)w.remove();if(o)o.remove();ensure();},0)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
</script>
)HTML";
