#pragma once

#include <Arduino.h>

// Additive Erweiterungen fuer Statusanzeigen und Bedienoberflaeche.
static const char WEB_UI_PATCH[] PROGMEM = R"HTML(
<style>
.tabpanel{border-radius:0 0 12px 12px!important}
.beta{font-size:.63rem;font-weight:700;letter-spacing:.04em;border:1px solid #8a5a00;color:#8a5a00;border-radius:999px;padding:2px 5px;margin-left:2px}
.headDate{display:inline-block!important}.headWeek{display:inline-block;margin-left:6px;font-size:.74rem;color:var(--muted)}
.usageBlock{margin-top:13px}.usageRow{margin-top:10px}.usageHead{display:flex;justify-content:space-between;gap:12px;font-size:.8rem;color:var(--muted);margin-bottom:4px}.usageHead b{color:var(--text);font-weight:600}.usageBar{height:10px;background:var(--line);border-radius:6px;overflow:hidden}.usageBar>span{display:block;height:100%;width:0;background:var(--accent);transition:width .2s ease}
.themeSwitch{padding-bottom:27px}.themeSwitch .actionUnit{position:relative;display:inline-flex;align-items:center!important;gap:0;flex:0 0 auto}.themeSwitch .actionMessage{position:absolute;top:calc(100% + 5px);left:50%;transform:translateX(-50%);max-width:none;white-space:nowrap;pointer-events:none}.themeSwitch button{position:relative;flex:none}.themeSwitch button[data-theme-choice="system"]{width:88px}.themeSwitch button[data-theme-choice="light"],.themeSwitch button[data-theme-choice="dark"]{width:44px;padding-left:0!important;padding-right:0!important}.themeSwitch button.active{background:var(--accent)!important;color:#fff!important;border-color:var(--accent)!important;box-shadow:0 0 0 2px rgba(33,102,209,.18)}.themeSwitch button.actionRunning::after,.themeSwitch button.actionSuccess::after,.themeSwitch button.actionError::after{position:absolute;right:3px;top:2px;line-height:1;font-size:.68rem;pointer-events:none}
#languageSelect{display:none!important}.languageSwitch{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.languageSwitch button{min-width:82px}.languageSwitch button.active{background:var(--accent)!important;color:#fff!important;border-color:var(--accent)!important;box-shadow:0 0 0 2px rgba(33,102,209,.16)}
/* Sprache und Darstellung verwenden identische Auswahlbuttons. */
section#settings .languageSwitch,section#settings .themeSwitch{display:flex!important;flex-wrap:nowrap!important;gap:6px!important;align-items:flex-start!important;width:max-content;max-width:none}
section#settings .languageSwitch button[data-language-choice],section#settings .themeSwitch button[data-theme-choice]{box-sizing:border-box!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;position:relative!important;flex:0 0 104px!important;width:104px!important;min-width:104px!important;max-width:104px!important;height:40px!important;min-height:40px!important;padding:9px 13px!important;white-space:nowrap!important}
section#settings .themeSwitch .actionUnit{flex:0 0 104px!important;width:104px!important;min-width:104px!important;max-width:104px!important}
section#settings .languageSwitch button.actionRunning::after,section#settings .languageSwitch button.actionSuccess::after,section#settings .languageSwitch button.actionError::after,section#settings .themeSwitch button.actionRunning::after,section#settings .themeSwitch button.actionSuccess::after,section#settings .themeSwitch button.actionError::after{right:4px!important;top:3px!important;font-size:.66rem!important;line-height:1!important}
.countAction.fastFeedback{transform:scale(.91);background:var(--card);border-color:var(--accent);box-shadow:0 0 0 4px rgba(33,102,209,.18)}.countAction.delete.fastFeedback{border-color:var(--danger);box-shadow:0 0 0 4px rgba(180,35,24,.16)}
.exportArchiveCard{grid-column:span 12}.exportArchiveMeta,.exportMeta{margin-top:10px;font-size:.8rem;color:var(--muted)}
.ringPurpose{margin:0 0 12px;line-height:1.45}.ringPurpose strong{font-weight:700}
#devHeap.slowMetric{position:relative;display:inline-block;min-width:82px;color:transparent!important;white-space:nowrap}#devHeap.slowMetric::after{content:attr(data-visible-value);position:absolute;right:0;top:0;color:var(--text);font-variant-numeric:tabular-nums;white-space:nowrap}
#oledPreviewMeta{display:none!important}
#displayCard.moduleCard.unavailable{opacity:1!important;filter:none!important}
#displayCard.moduleCard.unavailable>h3{opacity:.58}
#displayCard.moduleCard.unavailable>#oledPreviewBlock,#displayCard.moduleCard.unavailable>.settingsRow,#displayCard.moduleCard.unavailable>.displayAdvanced,#displayCard.moduleCard.unavailable>.actions,#displayCard.moduleCard.unavailable>p.infoHelp{opacity:.38;filter:grayscale(1)}
#displayCard.moduleCard.unavailable>#displaySimulationRow{opacity:1!important;filter:none!important;border-color:var(--accent)}
@media(max-width:800px){.exportArchiveCard{grid-column:span 12}}
</style>
<script>
(function(){'use strict';
const $=id=>document.getElementById(id);
const locale=()=>window.UicI18n&&window.UicI18n.locale?window.UicI18n.locale():'de-DE';
const fmt=n=>new Intl.NumberFormat(locale()).format(Number(n||0));
let webEventCount=null;
let lastSlowMetricsAt=0;
function pct(a,b){return b>0?Math.max(0,Math.min(100,a/b*100)):0}
function setText(el,value){if(el&&el.textContent!==value)el.textContent=value}
function uiText(key,fallback){return window.uicTr?window.uicTr(key):fallback}
function bytesStable(n){n=Number(n||0);if(n<1024)return Math.round(n)+' B';if(n<1048576)return(n/1024).toFixed(1)+' KiB';return(n/1048576).toFixed(2)+' MiB'}
function makeSlowMetric(id){const el=$(id);if(!el)return;el.classList.add('slowMetric');if(!el.dataset.visibleValue)el.dataset.visibleValue=el.textContent||'-'}
function setSlowMetric(id,value){const el=$(id);if(!el)return;makeSlowMetric(id);if(el.dataset.visibleValue!==value)el.dataset.visibleValue=value}
function isoWeekFromDevice(){let el=$('deviceDateHead'),out=$('headWeek');if(!el||!out)return;let m=(el.textContent||'').match(/(\d{2})\.(\d{2})\.(\d{4})/);if(!m){setText(out,'');return}let d=new Date(Date.UTC(+m[3],+m[2]-1,+m[1])),day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);let y=new Date(Date.UTC(d.getUTCFullYear(),0,1));let w=Math.ceil((((d-y)/86400000)+1)/7);setText(out,uiText('dynamic.week_prefix','KW ')+w)}
function addWeek(){let date=$('deviceDateHead');if(!date||$('headWeek'))return;let s=document.createElement('span');s.id='headWeek';s.className='headWeek';date.insertAdjacentElement('afterend',s);isoWeekFromDevice()}
function addBeta(){let tab=document.querySelector('.tab[data-view="autark"]');if(!tab||tab.querySelector('.beta'))return;let b=document.createElement('span');b.className='beta';b.textContent='BETA';tab.appendChild(b)}
function updateThemeButtons(){let current=localStorage.getItem('uic-theme')||'system';document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===current))}
function clearOldThemeFeedback(active){document.querySelectorAll('.themeSwitch .actionUnit').forEach(unit=>{const button=unit.querySelector('button');if(!button||button===active)return;button.classList.remove('actionRunning','actionSuccess','actionError');const message=unit.querySelector('.actionMessage');if(message){message.className='actionMessage';message.textContent=''}})}
function hookTheme(){document.querySelectorAll('[data-theme-choice]').forEach(b=>{if(b.dataset.themePatchHook)return;b.dataset.themePatchHook='1';b.addEventListener('click',()=>setTimeout(()=>{updateThemeButtons();clearOldThemeFeedback(b)},0))});updateThemeButtons()}
function makeMeter(parent,id,label){if(!parent||$(id))return;let row=document.createElement('div');row.className='usageRow';row.innerHTML='<div class="usageHead"><span>'+label+'</span><b id="'+id+'Text">-</b></div><div class="usageBar"><span id="'+id+'Bar"></span></div>';parent.appendChild(row)}
function setMeter(id,used,total,labelUsed){let b=$(id+'Bar'),t=$(id+'Text');if(!b||!t)return;const width=pct(used,total).toFixed(1)+'%';if(b.style.width!==width)b.style.width=width;const value=labelUsed||fmt(used)+' / '+fmt(total);setText(t,value)}
function addMeters(){let boxes=document.querySelectorAll('#device .infoBox');if(boxes.length<4)return;let sys=document.createElement('div');sys.className='usageBlock';boxes[0].appendChild(sys);makeMeter(sys,'meterRam',uiText('dynamic.ram_usage','RAM-Auslastung'));makeMeter(sys,'meterFlash',uiText('dynamic.program_storage','Programmspeicher'));let store=document.createElement('div');store.className='usageBlock';boxes[2].appendChild(store);makeMeter(store,'meterRecent',uiText('storage.normal_ring','Normal-Ringspeicher'));makeMeter(store,'meterArchive',uiText('storage.long_ring','Langzeit-Ringspeicher'));makeMeter(store,'meterAutark',uiText('storage.autark_ring','Autark-Ringspeicher'));let fs=document.createElement('div');fs.className='usageBlock';boxes[3].appendChild(fs);makeMeter(fs,'meterFs','LittleFS')}
function addBaseExportMeta(){let normal=document.querySelector('#export a[href="/export.csv"]'),autark=document.querySelector('#export a[href="/autark.csv"]');if(normal&&!$('recentExportMeta'))normal.insertAdjacentHTML('afterend','<div id="recentExportMeta" class="exportMeta"></div>');if(autark&&!$('autarkExportMeta'))autark.insertAdjacentHTML('afterend','<div id="autarkExportMeta" class="exportMeta"></div>')}
function addArchiveExport(){let grid=document.querySelector('#export .grid');if(!grid||$('archiveExportCard'))return;let c=document.createElement('div');c.id='archiveExportCard';c.className='card exportArchiveCard';c.innerHTML='<h2>💾 '+uiText('storage.long_ring','Langzeit-Ringspeicher')+'</h2><p class="ringPurpose"></p><a class="btn primary" href="/archive.csv">'+uiText('export.long_csv','Langzeit-Ringspeicher als CSV')+'</a><div id="archiveExportMeta" class="exportArchiveMeta"></div>';grid.appendChild(c)}
function setPreviousLabel(valueId,label){let value=$(valueId),node=value&&value.previousElementSibling;if(node)setText(node,label)}
function setMeterLabel(id,label){let value=$(id+'Text'),head=value&&value.closest('.usageHead'),node=head&&head.querySelector('span');setText(node,label)}
function configureExportCard(href,title,purpose,buttonText){let link=document.querySelector('#export a[href="'+href+'"]'),card=link&&link.closest('.card');if(!card)return;let heading=card.querySelector('h2');if(heading){const next='💾 '+title;if(heading.textContent!==next)heading.textContent=next}let purposeNode=card.querySelector('.ringPurpose'),oldParagraph=card.querySelector('p');if(!purposeNode){purposeNode=document.createElement('p');purposeNode.className='ringPurpose';if(oldParagraph)oldParagraph.replaceWith(purposeNode);else if(heading)heading.insertAdjacentElement('afterend',purposeNode)}const purposeHtml='<strong>'+uiText('storage.purpose','Zweck:')+'</strong> '+purpose;if(purposeNode.innerHTML!==purposeHtml)purposeNode.innerHTML=purposeHtml;setText(link,buttonText)}
function normalizeStorageUi(){let normal=uiText('storage.normal_ring','Normal-Ringspeicher'),archive=uiText('storage.long_ring','Langzeit-Ringspeicher'),autark=uiText('storage.autark_ring','Autark-Ringspeicher');setPreviousLabel('devRecent',normal);setPreviousLabel('devArchive',archive);setPreviousLabel('devAutark',autark);setMeterLabel('meterRecent',normal);setMeterLabel('meterArchive',archive);setMeterLabel('meterAutark',autark);setMeterLabel('meterRam',uiText('dynamic.ram_usage','RAM-Auslastung'));setMeterLabel('meterFlash',uiText('dynamic.program_storage','Programmspeicher'));configureExportCard('/export.csv',normal,uiText('storage.normal_purpose','Schneller Ringspeicher für die letzten Unterbrechungen und die Webansicht.'),uiText('export.normal_csv','Normal-Ringspeicher als CSV'));configureExportCard('/autark.csv',autark,uiText('storage.autark_purpose','Speichert Autark-Sessions, Pulse, relative Zeiten und Zeitanker.'),uiText('export.autark_csv','Autark-Ringspeicher als CSV'));configureExportCard('/archive.csv',archive,uiText('storage.long_purpose','Langzeitbasis für Statistik, Heatmaps und den vollständigen Archivexport.'),uiText('export.long_csv','Langzeit-Ringspeicher als CSV'))}
function renameOverview(){let s=$('displayLayout');if(!s)return;let o=s.querySelector('option[value="0"]');if(o)setText(o,uiText('display.daily_overview','Tagesübersicht'))}
function exportMeta(id,count,capacity){let el=$(id);setText(el,uiText('storage.used','Belegt: ')+fmt(count)+' / '+fmt(capacity))}
function updateFromStatus(d){if(!d)return;setMeter('meterRecent',d.eventCount,d.ringCapacity);setMeter('meterArchive',d.archiveCount,d.archiveCapacity);setMeter('meterAutark',d.autarkCount,d.autarkCapacity);exportMeta('recentExportMeta',d.eventCount,d.ringCapacity);exportMeta('archiveExportMeta',d.archiveCount,d.archiveCapacity);exportMeta('autarkExportMeta',d.autarkCount,d.autarkCapacity);const now=Date.now();if(!lastSlowMetricsAt||now-lastSlowMetricsAt>=10000){lastSlowMetricsAt=now;setSlowMetric('devHeap',bytesStable(d.heapFree));setMeter('meterFs',d.fsUsed,d.fsTotal);let heapTotal=Number(d.heapTotal||0);setMeter('meterRam',Math.max(0,heapTotal-Number(d.heapFree||0)),heapTotal);let sketchTotal=Number(d.sketchUsed||0)+Number(d.sketchFree||0);setMeter('meterFlash',d.sketchUsed,sketchTotal)}}
function hookFetch(){const original=window.fetch.bind(window);window.fetch=async function(){let args=arguments,u=String(args[0]||''),r=await original.apply(null,args);try{if(u.indexOf('/api/events')>=0&&r.ok)r.clone().json().then(d=>{webEventCount=(d.events||[]).length}).catch(()=>{});if(u.indexOf('/api/status')>=0&&r.ok){let d=await r.clone().json();let view=Object.assign({},d);if(view.deviceTime&&String(view.deviceTime).length>=5)view.deviceTime=String(view.deviceTime).substring(0,5);if(webEventCount!==null)view.eventCount=webEventCount;setTimeout(()=>updateFromStatus(view),0);return new Response(JSON.stringify(view),{status:r.status,statusText:r.statusText,headers:r.headers})}}catch(e){}return r}}
function fastButton(id,delta,url){let b=$(id);if(!b)return;b.onclick=async function(){let n=$('todayCount'),old=Number((n.textContent||'0').replace(/\D/g,''))||0;if(n)setText(n,String(Math.max(0,old+delta)));b.classList.add('fastFeedback');setTimeout(()=>b.classList.remove('fastFeedback'),180);if(webEventCount!==null)webEventCount=Math.max(0,webEventCount+delta);try{let r=await fetch(url,{method:'POST',cache:'no-store'});if(!r.ok)throw new Error(await r.text());if(window.uicLoadDisplayPreview)window.uicLoadDisplayPreview()}catch(e){if(n)setText(n,String(old));if(webEventCount!==null)webEventCount=Math.max(0,webEventCount-delta);let notice=$('notice');if(notice){notice.style.display='block';setText(notice,e.message||String(e))}}}}
function currentLanguage(){return localStorage.getItem('uic-lang')||'de'}
function updateLanguageButtons(){const current=currentLanguage();document.querySelectorAll('#languageButtons [data-language-choice]').forEach(button=>button.classList.toggle('active',button.dataset.languageChoice===current))}
function showLanguageFeedback(button){if(!button)return;document.querySelectorAll('#languageButtons [data-language-choice]').forEach(other=>{if(other===button)return;other.classList.remove('actionRunning','actionSuccess','actionError');clearTimeout(other._languageStateTimer)});button.classList.remove('actionRunning','actionSuccess','actionError');button.classList.add('actionSuccess');clearTimeout(button._languageStateTimer);button._languageStateTimer=setTimeout(()=>button.classList.remove('actionSuccess'),1400)}
function chooseLanguage(code,button){const select=$('languageSelect');if(!select||!code)return;if(select.value!==code)select.value=code;localStorage.setItem('uic-lang',code);showLanguageFeedback(button);select.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(()=>{updateLanguageButtons();applyStaticUi()},40)}
function buildLanguageButtons(){const select=$('languageSelect');if(!select)return;select.hidden=true;select.setAttribute('aria-hidden','true');select.tabIndex=-1;let group=$('languageButtons');if(!group){group=document.createElement('div');group.id='languageButtons';group.className='languageSwitch';select.insertAdjacentElement('afterend',group)}const wanted=new Set();[...select.options].forEach(option=>{wanted.add(option.value);let button=group.querySelector('[data-language-choice="'+option.value+'"]');if(!button){button=document.createElement('button');button.type='button';button.dataset.languageChoice=option.value;button.addEventListener('click',()=>chooseLanguage(option.value,button));group.appendChild(button)}setText(button,option.textContent)});group.querySelectorAll('[data-language-choice]').forEach(button=>{if(!wanted.has(button.dataset.languageChoice))button.remove()});updateLanguageButtons()}
function applyStaticUi(){addWeek();addBaseExportMeta();normalizeStorageUi();renameOverview();hookTheme();buildLanguageButtons();isoWeekFromDevice()}
function init(){addWeek();addBeta();addMeters();addBaseExportMeta();addArchiveExport();normalizeStorageUi();hookTheme();makeSlowMetric('devHeap');hookFetch();fastButton('addBtn',1,'/api/add');fastButton('undoBtn',-1,'/api/delete-last');buildLanguageButtons();let language=$('languageSelect');if(language)language.addEventListener('change',()=>setTimeout(()=>{applyStaticUi();updateLanguageButtons()},100));setTimeout(renameOverview,150);setTimeout(applyStaticUi,500);setInterval(isoWeekFromDevice,30000)}
init();
})();
</script>
)HTML";
