#pragma once

#include <Arduino.h>

// Geraeteansicht fuer echte Hardwarezustaende. Die Anzeige verwendet bewusst
// nur gespeicherte Ergebnisse echter Hardwarepruefungen; zwischen zwei Checks
// bleibt der letzte Zustand sichtbar und wird nicht durch UI-Polling veraendert.
static const char WEB_UI_HARDWARE[] PROGMEM = R"HTML(
<style>
.v2Dot.warn{background:#d49a00!important}
.hw214Grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:12px}
.hw214Module{border:1px solid var(--line);border-radius:10px;padding:14px;background:var(--bg);min-width:0}
.hw214Module h4{margin:0 0 11px;font-size:.95rem;display:flex;align-items:center;gap:7px}
.hw214Kv{display:grid;grid-template-columns:minmax(110px,1fr) minmax(90px,1.2fr);gap:7px 12px;font-size:.82rem;margin-top:10px}
.hw214Kv span:nth-child(odd){color:var(--muted)}.hw214Kv span:nth-child(even){font-weight:600;overflow-wrap:anywhere}
.hw214Actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:13px}.hw214Actions button{min-height:36px}
.hw214Result{font-size:.78rem;color:var(--muted);margin-top:8px;min-height:1em}.hw214Result.ok{color:var(--ok)}.hw214Result.bad{color:var(--danger)}
.hw214Info{font-size:.78rem;color:var(--muted);line-height:1.45;margin-top:12px}
.hw214WdActions{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:10px 0 4px}.hw214WdActions button{min-height:36px}.hw214WdResult{font-size:.78rem;color:var(--muted)}
@media(max-width:900px){.hw214Grid{grid-template-columns:1fr}}@media(min-width:901px) and (max-width:1180px){.hw214Grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
<script>
(function(){'use strict';
const $=id=>document.getElementById(id);
let latestHardware=null;
let refreshBusy=false;
function localText(de,en,swg){const texts={de:de,en:en,swg:swg};const code=(localStorage.getItem('uic-lang')||'de').toLowerCase();return texts[code]||de}
function ageText(value){let ms=Number(value);if(!Number.isFinite(ms)||ms>4000000000)return'-';let s=Math.max(0,Math.round(ms/1000));if(s<60)return s+' s';let m=Math.floor(s/60),r=s%60;if(m<60)return m+' min '+r+' s';let h=Math.floor(m/60);return h+' h '+(m%60)+' min'}
function setStatus(dotId,textId,kind,text){let dot=$(dotId),label=$(textId);if(dot)dot.className='v2Dot '+kind;if(label)label.textContent=text}
function sourceText(value){if(value==='ntp')return'NTP';if(value==='rtc')return'RTC';if(value==='browser')return localText('Browser','browser','Browser');return'-'}
function hardwareText(detected,checking){if(detected)return checking?localText('Hardware erkannt · Prüfung läuft','Hardware detected · check running','Hardware gfunda · Prüfung lauft'):localText('Hardware erkannt','Hardware detected','Hardware gfunda');if(checking)return localText('Hardwareprüfung läuft','Checking hardware','Hardwareprüfung lauft');return localText('Hardware nicht erkannt','Hardware not detected','Hardware ned gfunda')}
function ensureHardwareCard(){const grid=document.querySelector('#device .infoGrid');if(!grid||$('hardwareModulesCard'))return;let card=document.createElement('div');card.id='hardwareModulesCard';card.className='infoBox v2Full';card.innerHTML=`<h3>🔌 ${localText('Hardware-Module','Hardware modules','Hardware-Modul')}</h3>
<div class="hw214Grid">
 <section class="hw214Module" id="hwRtcCard"><h4>🕒 DS3231 RTC</h4><div class="v2StatusLine"><span id="hwRtcDot" class="v2Dot"></span><b id="hwRtcStatus">-</b></div><div class="hw214Kv"><span>${localText('RTC-Zeit','RTC time','RTC-Zeit')}</span><span id="hwRtcTime">-</span><span>${localText('Systemzeit','System time','Systemzeit')}</span><span id="hwSystemTime">-</span><span>${localText('Zeitquelle','Time source','Zeitquell')}</span><span id="hwTimeSource">-</span><span>${localText('Kommunikation','Communication','Kommunikation')}</span><span id="hwRtcComm">-</span><span>OSF</span><span id="hwRtcOsf">-</span><span>${localText('Temperatur','Temperature','Temperatur')}</span><span id="hwRtcTemp">-</span><span>${localText('Letzte Hardwareprüfung','Last hardware check','Letschte Hardwareprüfung')}</span><span id="hwRtcAge">-</span></div><div class="hw214Actions"><button id="hwRtcCheck">${localText('RTC prüfen','Check RTC','RTC prüfa')}</button><button id="hwSystemToRtc">${localText('System → RTC','System → RTC','System → RTC')}</button><button id="hwRtcToSystem">${localText('RTC → System','RTC → system','RTC → System')}</button></div><div id="hwRtcResult" class="hw214Result"></div></section>
 <section class="hw214Module" id="hwDisplayCard"><h4>🖥️ SH1106 OLED</h4><div class="v2StatusLine"><span id="hwDisplayDot" class="v2Dot"></span><b id="hwDisplayStatus">-</b></div><div class="hw214Kv"><span>${localText('I²C-Adresse','I²C address','I²C-Adress')}</span><span id="hwDisplayAddress">-</span><span>${localText('Displayzustand','Display state','Displayzustand')}</span><span id="hwDisplayActive">-</span><span>${localText('Simulation','Simulation','Simulation')}</span><span id="hwDisplaySimulation">-</span></div><p class="hw214Info">${localText('Der OLED-Status zeigt die beim Start erkannte Hardware. Bedienung und Simulation bleiben im Einstellungs-Reiter.','OLED status shows the hardware detected at boot. Controls and simulation remain in Settings.','Dr OLED-Status zeigt d Hardware vom Start. Bedienung ond Simulation bleibet bei de Einstellungen.')}</p></section>
 <section class="hw214Module" id="hwSoundCard"><h4>🔊 DY-SV17F</h4><div class="v2StatusLine"><span id="hwSoundDot" class="v2Dot"></span><b id="hwSoundStatus">-</b></div><div class="hw214Kv"><span>${localText('Funktion','Feature','Funktion')}</span><span id="hwSoundEnabled">-</span><span>${localText('Wiedergabe','Playback','Wiedergab')}</span><span id="hwSoundBusy">-</span><span>${localText('Letzte Hardwareprüfung','Last hardware check','Letschte Hardwareprüfung')}</span><span id="hwSoundAge">-</span><span>${localText('Automatische Prüfung','Automatic check','Automatische Prüfung')}</span><span>10 min</span></div><div class="hw214Actions"><button id="hwSoundCheck">${localText('Soundmodul prüfen','Check sound module','Soundmodul prüfa')}</button></div><div id="hwSoundResult" class="hw214Result"></div></section>
</div><p class="hw214Info">${localText('Hardware wird nicht bei jedem Webseitenaufruf neu abgefragt. Der zuletzt bestätigte Zustand bleibt bestehen und ändert sich erst bei einer echten Prüfung, bei Nutzung oder im vorgesehenen langen Prüfzyklus.','Hardware is not queried on every page refresh. The last confirmed state remains until a real check, actual use, or the scheduled long check runs.','D Hardware wird ned bei jedem Seitenaufruf neu gfragt. Dr letscht bestätigte Zustand bleibt, bis wirklich geprüft, benutzt oder im lange Zyklus kontrolliert wird.')}</p>`;let wd=$('watchdogCard');if(wd)grid.insertBefore(card,wd);else grid.appendChild(card);hookHardwareButtons()}
function ensureWatchdogReset(){let card=$('watchdogCard');if(!card||$('wdResetMax'))return;let box=document.createElement('div');box.className='hw214WdActions';box.innerHTML=`<button id="wdResetMax">${localText('Maximalwerte zurücksetzen','Reset maximum values','Maximalwert zrucksetza')}</button><span id="wdResetResult" class="hw214WdResult"></span>`;let help=card.querySelector('.infoHelp');if(help)card.insertBefore(box,help);else card.appendChild(box);$('wdResetMax').onclick=resetWatchdogMax}
async function post(path){let r=await fetch(path,{method:'POST',cache:'no-store'});let text=await r.text();if(!r.ok)throw new Error(text||('HTTP '+r.status));return text}
async function runRtcAction(path,success){let out=$('hwRtcResult');if(out){out.className='hw214Result';out.textContent='…'}try{await post(path);if(out){out.className='hw214Result ok';out.textContent=success}setTimeout(refreshHardware,150)}catch(e){if(out){out.className='hw214Result bad';out.textContent=localText('Aktion fehlgeschlagen.','Action failed.','Aktion hot ned klappt.')}}}
async function checkSound(){let out=$('hwSoundResult');if(out){out.className='hw214Result';out.textContent=localText('Prüfung läuft …','Checking …','Prüfung lauft …')}try{await post('/api/sound-check');setTimeout(refreshHardware,150);setTimeout(refreshHardware,1200);setTimeout(refreshHardware,3300)}catch(e){if(out){out.className='hw214Result bad';out.textContent=localText('Prüfung konnte nicht gestartet werden.','Check could not be started.','Prüfung hot ned startet.')}}}
async function resetWatchdogMax(){let out=$('wdResetResult');try{await post('/api/watchdog-reset-max');if(out)out.textContent=localText('Maximalwerte zurückgesetzt.','Maximum values reset.','Maximalwert zruckgsetzt.');setTimeout(()=>{if(out)out.textContent=''},3500)}catch(e){if(out)out.textContent=localText('Zurücksetzen fehlgeschlagen.','Reset failed.','Zrucksetza hot ned klappt.')}}
function hookHardwareButtons(){if($('hwRtcCheck'))$('hwRtcCheck').onclick=()=>runRtcAction('/api/rtc-check',localText('RTC geprüft.','RTC checked.','RTC geprüft.'));if($('hwSystemToRtc'))$('hwSystemToRtc').onclick=()=>runRtcAction('/api/rtc-from-system',localText('Systemzeit in RTC geschrieben.','System time written to RTC.','Systemzeit in d RTC gschrieba.'));if($('hwRtcToSystem'))$('hwRtcToSystem').onclick=()=>runRtcAction('/api/rtc-to-system',localText('RTC-Zeit als Systemzeit übernommen.','RTC time applied to system.','RTC-Zeit als Systemzeit gnomma.'));if($('hwSoundCheck'))$('hwSoundCheck').onclick=checkSound}
function applyHardware(d){latestHardware=d;let r=d.rtc||{},s=d.sound||{},o=d.display||{},sys=d.system||{};let rtcKind=!r.detected?'bad':(!r.communicationOk?'warn':'ok');let rtcLabel=hardwareText(!!r.detected,false);if(r.detected&&!r.communicationOk)rtcLabel+=' · '+localText('Kommunikation gestört','communication issue','Kommunikation gstöert');setStatus('hwRtcDot','hwRtcStatus',rtcKind,rtcLabel);if($('hwRtcTime'))$('hwRtcTime').textContent=(r.date||'-')+' · '+(r.time||'-');if($('hwSystemTime'))$('hwSystemTime').textContent=(sys.date||'-')+' · '+(sys.time||'-');if($('hwTimeSource'))$('hwTimeSource').textContent=sourceText(sys.source);if($('hwRtcComm'))$('hwRtcComm').textContent=r.communicationOk?localText('OK','OK','OK'):localText('Fehler','Error','Fehler');if($('hwRtcOsf'))$('hwRtcOsf').textContent=r.osf?localText('gesetzt · Zeit unsicher','set · time uncertain','gsetzt · Zeit unsicher'):'OK';if($('hwRtcTemp'))$('hwRtcTemp').textContent=r.temperatureC==null?'-':Number(r.temperatureC).toFixed(2)+' °C';if($('hwRtcAge'))$('hwRtcAge').textContent=ageText(r.checkAgeMs);
 let displayKind=o.detected?'ok':(o.simulation?'warn':'bad');let displayLabel=o.detected?hardwareText(true,false):(o.simulation?localText('Hardware nicht erkannt · Simulation aktiv','Hardware not detected · simulation active','Hardware ned gfunda · Simulation aktiv'):hardwareText(false,false));setStatus('hwDisplayDot','hwDisplayStatus',displayKind,displayLabel);if($('hwDisplayAddress'))$('hwDisplayAddress').textContent=o.detected?'0x'+Number(o.address||0).toString(16).toUpperCase().padStart(2,'0'):'-';if($('hwDisplayActive'))$('hwDisplayActive').textContent=o.active?localText('aktiv','active','aktiv'):localText('inaktiv','inactive','inaktiv');if($('hwDisplaySimulation'))$('hwDisplaySimulation').textContent=o.simulation?localText('aktiv','active','aktiv'):localText('aus','off','aus');
 let soundKind=s.detected?'ok':(s.checking?'warn':'bad');setStatus('hwSoundDot','hwSoundStatus',soundKind,hardwareText(!!s.detected,!!s.checking));if($('hwSoundEnabled'))$('hwSoundEnabled').textContent=s.enabled?localText('aktiv','enabled','aktiv'):localText('deaktiviert','disabled','ausgschaltet');if($('hwSoundBusy'))$('hwSoundBusy').textContent=s.busy?localText('läuft','running','lauft'):localText('bereit','idle','bereit');if($('hwSoundAge'))$('hwSoundAge').textContent=ageText(s.checkAgeMs);let out=$('hwSoundResult');if(out&&s.checking){out.className='hw214Result';out.textContent=localText('Prüfung läuft …','Checking …','Prüfung lauft …')}else if(out&&out.textContent&&s.detected){out.className='hw214Result ok';out.textContent=localText('Hardware bestätigt.','Hardware confirmed.','Hardware bestätigt.')}
 decorateWatchdogHardware()}
function decorateWatchdogHardware(){if(!latestHardware)return;let body=$('watchdogRows');if(!body)return;let r=latestHardware.rtc||{},s=latestHardware.sound||{},o=latestHardware.display||{};[...body.rows].forEach(row=>{let name=row.cells[0]&&row.cells[0].textContent.trim(),cell=row.querySelector('.v212Hardware');if(!cell)return;if(name==='RTC')cell.textContent='DS3231 · '+(r.detected?localText('erkannt','detected','gfunda'):localText('nicht erkannt','not detected','ned gfunda'))+' · '+localText('Prüfung ','check ','Prüfung ')+ageText(r.checkAgeMs);else if(name==='Sound')cell.textContent='DY-SV17F · '+(s.detected?localText('erkannt','detected','gfunda'):localText('nicht erkannt','not detected','ned gfunda'))+' · '+localText('Prüfung ','check ','Prüfung ')+ageText(s.checkAgeMs);else if(name==='Display')cell.textContent='OLED · '+(o.detected?localText('erkannt','detected','gfunda'):(o.simulation?localText('Simulation','simulation','Simulation'):localText('nicht erkannt','not detected','ned gfunda')))})}
async function refreshHardware(){if(refreshBusy)return;refreshBusy=true;try{let r=await fetch('/api/device-hardware',{cache:'no-store'});if(r.ok)applyHardware(await r.json())}catch(e){}finally{refreshBusy=false}}
function init(){ensureHardwareCard();ensureWatchdogReset();refreshHardware();setInterval(refreshHardware,5000);let rows=$('watchdogRows');if(rows)new MutationObserver(()=>setTimeout(decorateWatchdogHardware,10)).observe(rows,{childList:true,subtree:true});let language=$('languageSelect');if(language)language.addEventListener('change',()=>setTimeout(()=>{let card=$('hardwareModulesCard');if(card)card.remove();ensureHardwareCard();ensureWatchdogReset();applyHardware(latestHardware||{})},20))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
</script>
)HTML";
