#pragma once

#include <Arduino.h>

// UI-Erweiterungen fuer 2.1.0. Die bestehende 1.0.1-Oberflaeche bleibt die Basis;
// neue Module werden mit denselben Karten, Buttons, Hardware-Icons und Sprachregeln
// in die vorhandenen Bereiche Einstellungen und Geraet eingesetzt.
static const char WEB_UI_V2[] PROGMEM = R"HTML(
<style>
.v2Full{grid-column:1/-1}.v2StatusLine{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:12px}.v2Dot{width:9px;height:9px;border-radius:50%;background:var(--muted);display:inline-block}.v2Dot.ok{background:var(--ok)}.v2Dot.bad{background:var(--danger)}
.v2SoundCounters{margin-top:12px}.v2TrackBox{margin-top:14px;border-top:1px solid var(--line);padding-top:12px}.v2TrackBox summary{cursor:pointer;font-weight:600;margin-bottom:10px}.v2TrackWrap{max-height:340px;overflow:auto;border:1px solid var(--line);border-radius:9px}.v2TrackTable{width:100%;border-collapse:collapse}.v2TrackTable th,.v2TrackTable td{padding:7px 9px;border-bottom:1px solid var(--line);text-align:left}.v2TrackTable th:first-child,.v2TrackTable td:first-child{width:70px;text-align:center}.v2TrackTable input{width:100%;min-width:130px}
.v2WdWrap{overflow:auto}.v2WdTable{width:100%;border-collapse:collapse;min-width:720px}.v2WdTable th,.v2WdTable td{padding:7px 9px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap}.v2WdTable td.ok{color:var(--ok);font-weight:600}.v2WdTable td.warn{color:var(--accent);font-weight:600}.v2WdTable td.off{color:var(--muted);font-weight:600}.v2WdTable td.bad{color:var(--danger);font-weight:600}.v2WdTable td.num{font-variant-numeric:tabular-nums;text-align:right}.v2WdTable th.num{text-align:right}
.v2OtaRow{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.v2OtaRow input[type=file]{max-width:100%}.v2Hint{font-size:.8rem;color:var(--muted);line-height:1.45;margin-top:9px}.v2Result{font-size:.8rem;color:var(--muted);margin-top:8px}.v2Result.ok{color:var(--ok)}.v2Result.bad{color:var(--danger)}
#soundSave,#soundTest,#trackListSave,#otaInstall{display:inline-flex;align-items:center;justify-content:center;position:relative;min-height:40px}#soundSave,#trackListSave,#otaInstall{background:var(--accent);border-color:var(--accent);color:#fff}
.v2Check{display:inline-flex;align-items:center;gap:7px}.v2Check input{width:18px;height:18px}.v2Range{display:grid;grid-template-columns:1fr 82px;gap:8px;align-items:center}.v2Range input[type=range]{width:100%;padding:0}
@media(max-width:520px){.v2Range{grid-template-columns:1fr 72px}.v2TrackWrap{max-height:280px}}
</style>
<script>
(function(){'use strict';
const $=id=>document.getElementById(id);
let soundSettingsLoaded=false;
const T={
 de:{
  sound_title:'DY-SV17F Soundmodul',sound_hw_ok:'Hardware erkannt',sound_hw_missing:'Hardware nicht erkannt',sound_hw_probe:'Hardwareprüfung läuft',sound_enabled:'Sound bei Unterbrechung',sound_volume:'Lautstärke',sound_track:'Track',sound_save:'Sound speichern',sound_test:'Testton',sound_sent:'Befehle gesendet',sound_done:'Erfolgreich abgeschlossen',sound_failed:'Fehlgeschlagen',sound_timeouts:'Timeouts',sound_responses:'Gültige Antworten',sound_errors:'UART/Protokollfehler',sound_help:'Das Soundmodul ist optional. Ein Track wird erst abgespielt, nachdem die Unterbrechung sicher gespeichert wurde. Ohne bestätigte DY-SV17F-Hardware bleibt der Zähler für gesendete Töne unverändert.',
  tracks_title:'Trackliste / Tonbelegung',tracks_help:'Hier steht, welcher nummerierte Track welcher Ton ist. Die Audiodateien selbst bleiben einmalig auf dem DY-SV17F; gespeichert werden hier nur die Beschreibungen.',tracks_num:'Track',tracks_name:'Beschreibung',tracks_save:'Trackliste speichern',tracks_saved:'Trackliste gespeichert.',tracks_error:'Trackliste konnte nicht gespeichert werden.',
  wd_title:'Watchdog / Moduldiagnose',wd_hw:'ESP32 Hardware-Watchdog aktiv',wd_module:'Modul',wd_status:'Status',wd_detail:'Detail',wd_age:'Letztes Lebenszeichen',wd_last:'Letzter Lauf',wd_max:'Maximum',wd_slow:'Langsam',wd_errors:'Fehler',wd_ok:'Bereit',wd_error:'FEHLER',wd_disabled:'Deaktiviert',wd_initializing:'Initialisierung',wd_busy:'Beschäftigt',wd_not_detected:'Nicht erkannt',wd_degraded:'Eingeschränkt',wd_timeout:'Timeout',wd_now:'jetzt',wd_help:'Rot bedeutet: Modulpfad liefert kein gültiges Lebenszeichen mehr. Ein langsamer Webrequest wird separat gezählt und ist nicht automatisch ein Watchdog-Fehler.',
  ota_title:'OTA Firmware',ota_choose:'Firmware-BIN auswählen',ota_install:'Firmware installieren',ota_none:'Bitte zuerst eine .bin-Datei auswählen.',ota_running:'Firmware wird übertragen …',ota_ok:'Update erfolgreich. Der ESP32 startet neu.',ota_error:'OTA-Update fehlgeschlagen.',ota_help:'Nur eine für diesen ESP32 erzeugte Firmware-BIN verwenden. WLAN-Zugangsdaten werden ab 2.0.0 persistent gespeichert und nicht mehr aus der OTA-Datei überschrieben.',
  saved:'Gespeichert.',save_error:'Speichern fehlgeschlagen.',test_started:'Testton gestartet.',test_missing:'Soundhardware ist nicht erkannt.',sound_icon:'DY-SV17F Soundmodul'
 },
 en:{
  sound_title:'DY-SV17F sound module',sound_hw_ok:'Hardware detected',sound_hw_missing:'Hardware not detected',sound_hw_probe:'Checking hardware',sound_enabled:'Sound on interruption',sound_volume:'Volume',sound_track:'Track',sound_save:'Save sound',sound_test:'Test sound',sound_sent:'Commands sent',sound_done:'Completed successfully',sound_failed:'Failed',sound_timeouts:'Timeouts',sound_responses:'Valid responses',sound_errors:'UART/protocol errors',sound_help:'The sound module is optional. A track is triggered only after the interruption has been stored safely. Without confirmed DY-SV17F hardware the sent-sound counter does not increase.',
  tracks_title:'Track list / sound assignment',tracks_help:'Use this list to record which numbered track contains which sound. Audio files stay on the DY-SV17F; only the descriptions are stored here.',tracks_num:'Track',tracks_name:'Description',tracks_save:'Save track list',tracks_saved:'Track list saved.',tracks_error:'Track list could not be saved.',
  wd_title:'Watchdog / module diagnostics',wd_hw:'ESP32 hardware watchdog active',wd_module:'Module',wd_status:'Status',wd_detail:'Detail',wd_age:'Last heartbeat',wd_last:'Last run',wd_max:'Maximum',wd_slow:'Slow',wd_errors:'Errors',wd_ok:'Ready',wd_error:'ERROR',wd_disabled:'Disabled',wd_initializing:'Initializing',wd_busy:'Busy',wd_not_detected:'Not detected',wd_degraded:'Degraded',wd_timeout:'Timeout',wd_now:'now',wd_help:'Red means that a module path no longer provides a valid heartbeat. A slow web request is counted separately and is not automatically a watchdog error.',
  ota_title:'OTA firmware',ota_choose:'Select firmware BIN',ota_install:'Install firmware',ota_none:'Please select a .bin file first.',ota_running:'Uploading firmware …',ota_ok:'Update successful. The ESP32 is restarting.',ota_error:'OTA update failed.',ota_help:'Use only firmware built for this ESP32. From 2.0.0 onward Wi-Fi credentials are stored persistently and are no longer replaced by the OTA file.',
  saved:'Saved.',save_error:'Save failed.',test_started:'Test sound started.',test_missing:'Sound hardware is not detected.',sound_icon:'DY-SV17F sound module'
 },
 swg:{
  sound_title:'DY-SV17F Krachmacher',sound_hw_ok:'Hardware gfunda',sound_hw_missing:'Hardware ned gfunda',sound_hw_probe:'I guck nach dr Hardware',sound_enabled:'Bei dr Unterbrechung Krach macha',sound_volume:'Lautstärk',sound_track:'Track',sound_save:'Sound speichera',sound_test:'Ton ausprobiera',sound_sent:'Befehle nausgschickt',sound_done:'Sauber fertig',sound_failed:'Daneba ganga',sound_timeouts:'Timeouts',sound_responses:'Gültige Antworta',sound_errors:'UART-/Protokollfehler',sound_help:'Dr Krachmacher isch optional. Dr Ton kommt erscht dran, wenn d Unterbrechung sicher gspeichert isch. Wenn koi DY-SV17F wirklich antwortet, wird au koi Ton als gsendet gezählt.',
  tracks_title:'Tracklischt / welcher Ton isch wo',tracks_help:'Do kasch neischreiba, welcher Track welchen Krach macht. D Audiodateia bleibet einmal auf em DY-SV17F; do speichere mer bloß d Beschreibung.',tracks_num:'Track',tracks_name:'Beschreibung',tracks_save:'Tracklischt speichera',tracks_saved:'Tracklischt isch gspeichert.',tracks_error:'Tracklischt hot sich ned speichera lassa.',
  wd_title:'Watchdog / Moduldiagnose',wd_hw:'ESP32 Hardware-Watchdog isch aktiv',wd_module:'Modul',wd_status:'Status',wd_detail:'Detail',wd_age:'Letschtes Lebenszeicha',wd_last:'Letschter Lauf',wd_max:'Maximum',wd_slow:'Langsam',wd_errors:'Fehler',wd_ok:'Bereit',wd_error:'FEHLER',wd_disabled:'Ausgschaltet',wd_initializing:'Startet grad',wd_busy:'Schafft grad',wd_not_detected:'Ned gfunda',wd_degraded:'Eingeschränkt',wd_timeout:'Timeout',wd_now:'grad eben',wd_help:'Rot heißt: dr Modulpfad liefert koi gültigs Lebenszeicha meh. En langsamer Webrequest wird extra gezählt und isch ned automatisch en Watchdog-Fehler.',
  ota_title:'OTA Firmware',ota_choose:'Firmware-BIN aussucha',ota_install:'Firmware installiera',ota_none:'Such erscht a .bin-Datei aus.',ota_running:'Firmware wird rübergschoba …',ota_ok:'Update hot klappt. Dr ESP32 startet neu.',ota_error:'OTA-Update hot ned klappt.',ota_help:'Bloß a Firmware-BIN für genau den ESP32 neh. Ab 2.0.0 bleibet d WLAN-Zugangsdada dauerhaft gspeichert und werdet von dr OTA-Datei nemme plattgmacht.',
  saved:'Gspeichert.',save_error:'Speichera hot ned klappt.',test_started:'Testton lauft.',test_missing:'Soundhardware isch ned gfunda.',sound_icon:'DY-SV17F Krachmacher'
 }
};
function lang(){const s=$('languageSelect');if(s&&T[s.value])return s.value;const h=(document.documentElement.lang||'').toLowerCase();return T[h]?h:'de'}
function tr(k){return (T[lang()]||T.de)[k]||T.de[k]||k}
function base(){return ''}
async function api(path,opt){const r=await fetch(base()+path,Object.assign({cache:'no-store'},opt||{}));if(!r.ok){let t='';try{t=await r.text()}catch(e){}throw new Error(t||('HTTP '+r.status))}const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setText(root){(root||document).querySelectorAll('[data-v2]').forEach(el=>el.textContent=tr(el.dataset.v2))}
function soundStateText(d){let s=d.sound||{};if(s.present)return tr('sound_hw_ok');if(s.hardwareState==='probing'||(s.confirmations||0)>0)return tr('sound_hw_probe');return tr('sound_hw_missing')}
function moduleStateText(state){return ({ready:tr('wd_ok'),disabled:tr('wd_disabled'),initializing:tr('wd_initializing'),busy:tr('wd_busy'),not_detected:tr('wd_not_detected'),degraded:tr('wd_degraded'),timeout:tr('wd_timeout'),error:tr('wd_error')})[state]||state||'-'}
function moduleStateClass(state){if(state==='ready'||state==='busy')return 'ok';if(state==='disabled'||state==='not_detected')return 'off';if(state==='initializing'||state==='degraded')return 'warn';return 'bad'}
function ageText(v){v=Number(v);if(!Number.isFinite(v)||v>4000000000)return '-';if(v<1000)return tr('wd_now');return (v/1000).toFixed(v<10000?1:0)+' s'}
function us(v){v=Number(v||0);return v?new Intl.NumberFormat(lang()==='en'?'en-US':'de-DE').format(v)+' µs':'-'}

function ensureHeaderIcon(){let wrap=document.querySelector('.headModules');if(!wrap||$('headSound'))return;let i=document.createElement('span');i.id='headSound';i.className='hwIcon unavailable';i.textContent='🔊';i.title=tr('sound_icon');wrap.appendChild(i)}
function ensureSoundCard(){if($('soundCard'))return;const grid=document.querySelector('#settings .infoGrid'),display=$('displayCard');if(!grid)return;let c=document.createElement('div');c.id='soundCard';c.className='infoBox moduleCard';c.innerHTML=`<h3><span class="moduleIcon">🔊</span> <span data-v2="sound_title"></span></h3>
<div class="v2StatusLine"><span id="soundDot" class="v2Dot"></span><b id="soundHardware">-</b></div>
<div class="settingsRow"><span data-v2="sound_enabled"></span><label class="v2Check"><input id="soundEnabled" type="checkbox"><span data-v2="sound_enabled"></span></label></div>
<div class="settingsRow"><label for="soundVolume" data-v2="sound_volume"></label><div class="v2Range"><input id="soundVolume" type="range" min="0" max="30" step="1"><input id="soundVolumeNumber" type="number" min="0" max="30"></div></div>
<div class="settingsRow"><label for="soundTrack" data-v2="sound_track"></label><select id="soundTrack"></select></div>
<div class="actions"><button id="soundSave" class="btn primary" data-v2="sound_save"></button><button id="soundTest" data-v2="sound_test"></button></div><div id="soundResult" class="v2Result"></div>
<div class="kv v2SoundCounters"><span data-v2="sound_sent"></span><span id="soundSent">0</span><span data-v2="sound_done"></span><span id="soundDone">0</span><span data-v2="sound_failed"></span><span id="soundFailed">0</span><span data-v2="sound_timeouts"></span><span id="soundTimeouts">0</span><span data-v2="sound_responses"></span><span id="soundResponses">0</span><span data-v2="sound_errors"></span><span id="soundErrors">0</span></div>
<p class="infoHelp" data-v2="sound_help"></p>
<details class="v2TrackBox" open><summary data-v2="tracks_title"></summary><p class="v2Hint" data-v2="tracks_help"></p><div class="v2TrackWrap"><table class="v2TrackTable"><thead><tr><th data-v2="tracks_num"></th><th data-v2="tracks_name"></th></tr></thead><tbody id="trackRows"></tbody></table></div><div class="actions" style="margin-top:10px"><button id="trackListSave" class="btn primary" data-v2="tracks_save"></button></div><div id="trackResult" class="v2Result"></div></details>`;
if(display)display.insertAdjacentElement('afterend',c);else grid.appendChild(c);hookSound();setText(c)}
function ensureDeviceCards(){const grid=document.querySelector('#device .infoGrid');if(!grid)return;if(!$('watchdogCard')){let c=document.createElement('div');c.id='watchdogCard';c.className='infoBox v2Full';c.innerHTML=`<h3>🛡️ <span data-v2="wd_title"></span></h3><div class="v2StatusLine"><span class="v2Dot ok"></span><b data-v2="wd_hw"></b></div><div class="v2WdWrap"><table class="v2WdTable"><thead><tr><th data-v2="wd_module"></th><th data-v2="wd_status"></th><th data-v2="wd_detail"></th><th data-v2="wd_age"></th><th class="num" data-v2="wd_last"></th><th class="num" data-v2="wd_max"></th><th class="num" data-v2="wd_slow"></th><th class="num" data-v2="wd_errors"></th></tr></thead><tbody id="watchdogRows"></tbody></table></div><p class="infoHelp" data-v2="wd_help"></p>`;grid.appendChild(c)}if(!$('otaCard')){let c=document.createElement('div');c.id='otaCard';c.className='infoBox v2Full';c.innerHTML=`<h3>⬆️ <span data-v2="ota_title"></span></h3><div class="v2OtaRow"><input id="otaFile" type="file" accept=".bin,application/octet-stream"><button id="otaInstall" class="btn primary" data-v2="ota_install"></button></div><div id="otaResult" class="v2Result"></div><p class="infoHelp" data-v2="ota_help"></p>`;grid.appendChild(c);$('otaInstall').onclick=installOta}setText(grid)}
function hookSound(){const r=$('soundVolume'),n=$('soundVolumeNumber');if(r&&n){r.oninput=()=>n.value=r.value;n.oninput=()=>r.value=n.value}$('soundSave').onclick=saveSound;$('soundTest').onclick=testSound;$('trackListSave').onclick=saveTracks}
function buildTrackRows(map){let rows='',opts='';for(let i=1;i<=50;i++){let name=map[i]||'';rows+=`<tr><td>${i}</td><td><input data-v2-track="${i}" maxlength="120" value="${esc(name)}"></td></tr>`;opts+=`<option value="${i}">${i}${name?' – '+esc(name):''}</option>`}$('trackRows').innerHTML=rows;const s=$('soundTrack'),old=s.value;s.innerHTML=opts;if(old)s.value=old}
async function loadTracks(){try{const d=await api('/api/tracks');let map={};(d.tracks||[]).forEach(x=>map[x.id]=x.name);buildTrackRows(map)}catch(e){buildTrackRows({})}}
async function saveTracks(){let out=$('trackResult');out.className='v2Result';out.textContent='…';let body=[...document.querySelectorAll('[data-v2-track]')].map(x=>x.dataset.v2Track+'|'+x.value.replace(/[\r\n|]/g,' ')).join('\n');try{await api('/api/tracks',{method:'POST',headers:{'Content-Type':'text/plain'},body});out.className='v2Result ok';out.textContent=tr('tracks_saved');await loadTracks()}catch(e){out.className='v2Result bad';out.textContent=tr('tracks_error')}}
async function saveSound(){let out=$('soundResult');out.className='v2Result';out.textContent='…';let p=new URLSearchParams({enabled:$('soundEnabled').checked?'1':'0',volume:$('soundVolumeNumber').value,track:$('soundTrack').value});try{await api('/api/sound-settings?'+p.toString(),{method:'POST'});out.className='v2Result ok';out.textContent=tr('saved');await refresh()}catch(e){out.className='v2Result bad';out.textContent=tr('save_error')}}
async function testSound(){let out=$('soundResult');if(!$('headSound').classList.contains('available')){out.className='v2Result bad';out.textContent=tr('test_missing');return}try{await api('/api/sound-test',{method:'POST'});out.className='v2Result ok';out.textContent=tr('test_started')}catch(e){out.className='v2Result bad';out.textContent=tr('test_missing')}}
async function installOta(){let file=$('otaFile').files[0],out=$('otaResult');if(!file){out.className='v2Result bad';out.textContent=tr('ota_none');return}out.className='v2Result';out.textContent=tr('ota_running');$('otaInstall').disabled=true;let form=new FormData();form.append('firmware',file,file.name);try{await api('/api/ota',{method:'POST',body:form});out.className='v2Result ok';out.textContent=tr('ota_ok')}catch(e){out.className='v2Result bad';out.textContent=tr('ota_error');$('otaInstall').disabled=false}}
function applyStatus(d){let s=d.sound||{},icon=$('headSound'),dot=$('soundDot');if(icon){icon.classList.toggle('available',!!s.present);icon.classList.toggle('unavailable',!s.present);icon.title=tr('sound_icon')+' – '+soundStateText(d)}if(dot)dot.className='v2Dot '+(s.present?'ok':'bad');if($('soundHardware'))$('soundHardware').textContent=soundStateText(d);if(!soundSettingsLoaded){if($('soundEnabled'))$('soundEnabled').checked=!!s.enabled;if($('soundVolume'))$('soundVolume').value=s.volume||0;if($('soundVolumeNumber'))$('soundVolumeNumber').value=s.volume||0;if($('soundTrack'))$('soundTrack').value=String(s.track||1);soundSettingsLoaded=true;}if($('soundTest'))$('soundTest').disabled=!s.present;if($('soundSent'))$('soundSent').textContent=s.sent||0;if($('soundDone'))$('soundDone').textContent=s.completed||0;if($('soundFailed'))$('soundFailed').textContent=s.failed||0;if($('soundTimeouts'))$('soundTimeouts').textContent=s.timeouts||0;if($('soundResponses'))$('soundResponses').textContent=s.responses||0;if($('soundErrors'))$('soundErrors').textContent=s.errors||0;let rows=$('watchdogRows');if(rows)rows.innerHTML=(d.modules||[]).map(m=>`<tr><td>${esc(m.name)}</td><td class="${moduleStateClass(m.state)}">${moduleStateText(m.state)}</td><td>${esc(m.detail||'-')}</td><td>${ageText(m.ageMs)}</td><td class="num">${us(m.lastUs)}</td><td class="num">${us(m.maxUs)}</td><td class="num">${m.slow||0}</td><td class="num">${m.errors||0}</td></tr>`).join('')}
async function refresh(){ensureHeaderIcon();ensureSoundCard();ensureDeviceCards();setText(document);try{const d=await api('/api/status');applyStatus(d)}catch(e){let h=$('soundHardware');if(h)h.textContent='API offline'}}
function languageChanged(){setText(document);refresh()}
function init(){ensureHeaderIcon();ensureSoundCard();ensureDeviceCards();loadTracks();const s=$('languageSelect');if(s)s.addEventListener('change',languageChanged);new MutationObserver(()=>setText(document)).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});refresh();setInterval(refresh,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
</script>
)HTML";
