#pragma once

#include <Arduino.h>

// Gemeinsame Sprachschluessel, Bedienrueckmeldung und Fokusverhalten.
static const char WEB_UI_BEHAVIOR[] PROGMEM = R"HTML(
<style>
.stableStorageNumber{position:relative;color:transparent!important;min-width:130px;white-space:nowrap}.stableStorageNumber::after{content:attr(data-formatted);position:absolute;right:0;top:0;color:var(--text);font-weight:600;white-space:nowrap}
#devHeap,#devRecent,#devArchive,#devAutark,#fsTotal,#fsUsed,#fsFree,.usageHead b{font-variant-numeric:tabular-nums}.usageHead b{min-width:105px;text-align:right}
.countAction svg{width:25px;height:25px;display:block;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round;pointer-events:none}.countAction.add svg{width:27px;height:27px}
button,.btn{transition:transform .08s ease,background .15s ease,border-color .15s ease,color .15s ease,box-shadow .15s ease}button:active,.btn:active{transform:translateY(1px) scale(.98)}

#export .btn,#displaySave,#displayTest,#ntpSaveBtn,#rtcSync{display:inline-flex;align-items:center;justify-content:center;position:relative;min-height:40px;padding-right:29px!important;white-space:nowrap;background:var(--accent);border-color:var(--accent);color:#fff}
#export .btn:hover,#displaySave:hover,#displayTest:hover,#ntpSaveBtn:hover,#rtcSync:hover{filter:brightness(1.05)}
#export .btn.actionRunning,#displaySave.actionRunning,#displayTest.actionRunning,#ntpSaveBtn.actionRunning,#rtcSync.actionRunning,.actionRunning,.displayActionRunning{background:var(--accent)!important;border-color:var(--accent)!important;color:#fff!important;box-shadow:0 0 0 3px rgba(33,102,209,.16)!important}
#export .btn.actionSuccess,#displaySave.actionSuccess,#displayTest.actionSuccess,#ntpSaveBtn.actionSuccess,#rtcSync.actionSuccess,.actionSuccess,.displayActionSuccess{background:var(--ok)!important;border-color:var(--ok)!important;color:#fff!important;box-shadow:0 0 0 3px rgba(22,128,58,.15)!important}
#export .btn.actionError,#displaySave.actionError,#displayTest.actionError,#ntpSaveBtn.actionError,#rtcSync.actionError,.actionError,.displayActionError{background:var(--danger)!important;border-color:var(--danger)!important;color:#fff!important;box-shadow:0 0 0 3px rgba(180,35,24,.14)!important}
button.actionRunning,button.actionSuccess,button.actionError,.btn.actionRunning,.btn.actionSuccess,.btn.actionError{position:relative}
.actionRunning::after,.displayActionRunning::after{content:'…'}.actionSuccess::after,.displayActionSuccess::after{content:'✓'}.actionError::after,.displayActionError::after{content:'!'}
.actionRunning::after,.actionSuccess::after,.actionError::after,.displayActionRunning::after,.displayActionSuccess::after,.displayActionError::after{position:absolute!important;right:4px!important;top:3px!important;transform:none!important;font-size:.66rem!important;font-weight:800!important;line-height:1!important;pointer-events:none!important;width:10px;text-align:center}

.actionUnit{display:inline-flex;flex-direction:column;align-items:flex-start;gap:5px;max-width:100%}.actionUnit.center{align-items:center}.actionMessage{display:none;max-width:360px;font-size:.78rem;line-height:1.25;color:var(--muted)}.actionMessage.show{display:block}.actionMessage.ok{color:var(--ok)}.actionMessage.bad{color:var(--danger)}.actions{align-items:flex-start!important}#displayState,#rtcSyncState{display:none!important}
#export .actionUnit{max-width:none;width:max-content}#export .actionMessage{max-width:none;white-space:nowrap}
#settings .languageSwitch{display:flex!important;flex-wrap:nowrap!important;gap:6px;align-items:center;width:max-content;max-width:none}
#settings .languageSwitch button{flex:0 0 auto!important;min-width:82px;white-space:nowrap!important}
#settings .themeSwitch{display:flex!important;flex-wrap:nowrap!important;gap:5px;align-items:flex-start;width:max-content;max-width:none}
#settings .themeSwitch .actionUnit{flex:0 0 auto;max-width:none}
#settings .themeSwitch button{flex:0 0 auto!important;white-space:nowrap!important}
#settings .themeSwitch button[data-theme-choice="system"]{width:auto!important;min-width:112px!important;padding-left:13px!important;padding-right:24px!important}
#settings .themeSwitch button[data-theme-choice="light"],#settings .themeSwitch button[data-theme-choice="dark"]{width:44px!important;min-width:44px!important;padding-left:0!important;padding-right:0!important}
#hourBars .barrow.zeroHour .bar{width:0!important}
.heat td.heatFocus,.heat td:focus-visible{outline:2px solid var(--ok)!important;outline-offset:1px;border-color:var(--ok)!important;box-shadow:inset 0 0 0 1px var(--ok)!important}
</style>
<script>
(function(){'use strict';
const $=id=>document.getElementById(id);
const EXTRA_I18N={
 de:{
  'action.add.running':'Unterbrechung wird gespeichert …','action.add.success':'Unterbrechung gespeichert.','action.add.error':'Speichern fehlgeschlagen.','action.delete.running':'Letzte Unterbrechung wird gelöscht …','action.delete.success':'Letzte Unterbrechung gelöscht.','action.delete.error':'Löschen fehlgeschlagen.','action.ntp.running':'NTP-Server wird geprüft …','action.ntp.success':'NTP-Server geprüft und gespeichert.','action.ntp.error':'NTP-Prüfung fehlgeschlagen.','action.ntp.enter':'Bitte NTP-Server eintragen.','action.rtc.running':'RTC wird synchronisiert …','action.rtc.success':'RTC synchronisiert.','action.rtc.error':'RTC-Synchronisation fehlgeschlagen.','action.display_save.running':'Display-Einstellungen werden gespeichert …','action.display_save.success':'Display-Einstellungen gespeichert.','action.display_save.error':'Display-Einstellungen konnten nicht gespeichert werden.','action.display_test.running':'Display-Test wird gestartet …','action.display_test.success':'Display-Test gestartet.','action.display_test.error':'Display-Test konnte nicht gestartet werden.','action.download.running':'Download wird gestartet …','action.download.started':'Download gestartet.','action.theme.changed':'Darstellung geändert.',
  'dynamic.week_prefix':'KW ','dynamic.ram_usage':'RAM-Auslastung','dynamic.program_storage':'Programmspeicher','storage.normal_ring':'Normal-Ringspeicher','storage.long_ring':'Langzeit-Ringspeicher','storage.autark_ring':'Autark-Ringspeicher','storage.purpose':'Zweck:','storage.used':'Belegt: ','storage.normal_purpose':'Schneller Ringspeicher für die letzten Unterbrechungen und die Webansicht.','storage.autark_purpose':'Speichert Autark-Sessions, Pulse, relative Zeiten und Zeitanker.','storage.long_purpose':'Langzeitbasis für Statistik, Heatmaps und den vollständigen Archivexport.','export.normal_csv':'Normal-Ringspeicher als CSV','export.autark_csv':'Autark-Ringspeicher als CSV','export.long_csv':'Langzeit-Ringspeicher als CSV',
  'display.daily_overview':'Tagesübersicht','display.simulation_title':'Display-Simulation','display.simulation_off':'Simulation aus','display.simulate':'Simulieren','display.preview':'OLED Live-Vorschau','display.dim_brightness':'Helligkeit gedimmt','display.off_after':'Ganz ausschalten nach','display.off_help':'0 = im Normalbetrieb nie ganz ausschalten; Autark bleibt fest bei 15 s.','display.layout':'Layout','display.standard':'Standard','display.compact':'Kompakt','display.large_clock':'Große Uhr','display.wake':'Bei Ereignis aufwecken','display.invert':'Anzeige invertieren','display.rotate':'180° drehen','display.sim_help':'Die Simulation verwendet exakt denselben 128×64-Framebuffer wie das echte OLED. Ist keine Hardware angeschlossen, können damit Layout, Helligkeit, Dimmen, Ausschalten und Ereignisreaktionen vollständig in der Web-Vorschau getestet werden.','display.sim_switching':'Schalte Simulation …','display.sim_switch_error':'Simulation konnte nicht umgeschaltet werden.','display.save_button':'Display speichern','display.test_button':'Display testen','display.hw_plus_sim':'Hardware erkannt · Simulation zusätzlich aktiv','display.real_hw':'Echte Hardware erkannt','display.sim_no_hw':'Simulation aktiv · keine Hardware erkannt','display.no_hw_sim_off':'Keine Hardware erkannt · Simulation aus','display.sim_active_title':'OLED Simulation aktiv','display.not_present_title':'OLED nicht vorhanden','display.hardware_badge':'HARDWARE','display.simulation_badge':'SIMULATION','display.off':'AUS','display.dimmed':'GEDIMMT','display.on':'AN','display.off_overlay':'DISPLAY AUS',
  'network.signal':'Signal','network.rating':'Bewertung','network.very_good':'sehr gut','network.good':'gut','network.fair':'ausreichend','network.weak':'schwach','network.wifi_connected':'WLAN verbunden','network.local_ap':'Lokaler Zugangspunkt aktiv','network.offline':'Offline',
  'calendar.mon':'Mo','calendar.tue':'Di','calendar.wed':'Mi','calendar.thu':'Do','calendar.fri':'Fr','calendar.sat':'Sa','calendar.sun':'So','calendar.jan':'Jan','calendar.feb':'Feb','calendar.mar':'Mär','calendar.apr':'Apr','calendar.may':'Mai','calendar.jun':'Jun','calendar.jul':'Jul','calendar.aug':'Aug','calendar.sep':'Sep','calendar.oct':'Okt','calendar.nov':'Nov','calendar.dec':'Dez'
 },
 en:{
  'action.add.running':'Saving interruption …','action.add.success':'Interruption saved.','action.add.error':'Save failed.','action.delete.running':'Deleting last interruption …','action.delete.success':'Last interruption deleted.','action.delete.error':'Delete failed.','action.ntp.running':'Checking NTP server …','action.ntp.success':'NTP server checked and saved.','action.ntp.error':'NTP check failed.','action.ntp.enter':'Please enter an NTP server.','action.rtc.running':'Synchronizing RTC …','action.rtc.success':'RTC synchronized.','action.rtc.error':'RTC synchronization failed.','action.display_save.running':'Saving display settings …','action.display_save.success':'Display settings saved.','action.display_save.error':'Display settings could not be saved.','action.display_test.running':'Starting display test …','action.display_test.success':'Display test started.','action.display_test.error':'Display test could not be started.','action.download.running':'Starting download …','action.download.started':'Download started.','action.theme.changed':'Appearance changed.',
  'dynamic.week_prefix':'CW ','dynamic.ram_usage':'RAM usage','dynamic.program_storage':'Program storage','storage.normal_ring':'Normal ring buffer','storage.long_ring':'Long-term ring buffer','storage.autark_ring':'Standalone ring buffer','storage.purpose':'Purpose:','storage.used':'Stored: ','storage.normal_purpose':'Fast ring buffer for recent interruptions and the web interface.','storage.autark_purpose':'Stores standalone sessions, pulses, relative times and time anchors.','storage.long_purpose':'Long-term source for statistics, heatmaps and the complete archive export.','export.normal_csv':'Download normal ring buffer CSV','export.autark_csv':'Download standalone ring buffer CSV','export.long_csv':'Download long-term ring buffer CSV',
  'display.daily_overview':'Daily overview','display.simulation_title':'Display simulation','display.simulation_off':'Simulation off','display.simulate':'Simulate','display.preview':'OLED live preview','display.dim_brightness':'Dimmed brightness','display.off_after':'Switch off after','display.off_help':'0 = never switch off in normal mode; standalone remains fixed at 15 s.','display.layout':'Layout','display.standard':'Standard','display.compact':'Compact','display.large_clock':'Large clock','display.wake':'Wake on event','display.invert':'Invert display','display.rotate':'Rotate 180°','display.sim_help':'Simulation uses exactly the same 128×64 framebuffer as the real OLED. Without connected hardware, layout, brightness, dimming, switch-off and event reactions can all be tested in the web preview.','display.sim_switching':'Switching simulation …','display.sim_switch_error':'Simulation could not be changed.','display.save_button':'Save display','display.test_button':'Test display','display.hw_plus_sim':'Hardware detected · simulation also active','display.real_hw':'Real hardware detected','display.sim_no_hw':'Simulation active · no hardware detected','display.no_hw_sim_off':'No hardware detected · simulation off','display.sim_active_title':'OLED simulation active','display.not_present_title':'OLED not present','display.hardware_badge':'HARDWARE','display.simulation_badge':'SIMULATION','display.off':'OFF','display.dimmed':'DIMMED','display.on':'ON','display.off_overlay':'DISPLAY OFF',
  'network.signal':'Signal','network.rating':'Rating','network.very_good':'very good','network.good':'good','network.fair':'fair','network.weak':'weak','network.wifi_connected':'Wi-Fi connected','network.local_ap':'Local access point active','network.offline':'Offline',
  'calendar.mon':'Mon','calendar.tue':'Tue','calendar.wed':'Wed','calendar.thu':'Thu','calendar.fri':'Fri','calendar.sat':'Sat','calendar.sun':'Sun','calendar.jan':'Jan','calendar.feb':'Feb','calendar.mar':'Mar','calendar.apr':'Apr','calendar.may':'May','calendar.jun':'Jun','calendar.jul':'Jul','calendar.aug':'Aug','calendar.sep':'Sep','calendar.oct':'Oct','calendar.nov':'Nov','calendar.dec':'Dec'
 },
 swg:{
  'action.add.running':'Kommt nei …','action.add.success':'Basst, isch gspeichert.','action.add.error':'Des hot ned klappt.','action.delete.running':'Letschtes fliegt wieder raus …','action.delete.success':'Letschtes Ding isch wieder weg.','action.delete.error':'Des wollt ned raus.','action.ntp.running':'I guck, ob dr NTP-Server do isch …','action.ntp.success':'NTP-Server basst und isch gspeichert.','action.ntp.error':'Dr NTP-Server will grad ned.','action.ntp.enter':'Trag erscht en NTP-Server ei.','action.rtc.running':'I richt d RTC grad …','action.rtc.success':'RTC läuft wieder grad.','action.rtc.error':'D RTC hot sich ned gradziaga lassa.','action.display_save.running':'I speicher s Display …','action.display_save.success':'Display-Eistellunga send gspeichert.','action.display_save.error':'Display-Eistellunga send ned gspeichert worda.','action.display_test.running':'I probier s Display aus …','action.display_test.success':'Display-Test läuft.','action.display_test.error':'Display-Test hot ned klappt.','action.download.running':'Download wird agschoba …','action.download.started':'Download lauft. D Dada send unterwegs.','action.theme.changed':'Ausseha isch umgstellt.',
  'dynamic.week_prefix':'KW ','dynamic.ram_usage':'RAM-Auslastung','dynamic.program_storage':'Programmspeicher','storage.normal_ring':'Normal-Ringspeicher','storage.long_ring':'Langzeit-Ringspeicher','storage.autark_ring':'Ohne-Netz-Ringspeicher','storage.purpose':'Wofür s gut isch:','storage.used':'Drin: ','storage.normal_purpose':'Schneller Ringspeicher für d letschte Unterbrechunga und d Webansicht.','storage.autark_purpose':'Speichert Ohne-Netz-Runda, Impuls, relative Zeita und Zeitanker.','storage.long_purpose':'Langzeitbasis für Statistik, Hitzekärtla und dr komplette Archivexport.','export.normal_csv':'Normal-Ringspeicher als CSV raustraga','export.autark_csv':'Ohne-Netz-Ringspeicher als CSV raustraga','export.long_csv':'Langzeit-Ringspeicher als CSV raustraga',
  'display.daily_overview':'Tagesüberblick','display.simulation_title':'Display bloß zum Gugga','display.simulation_off':'Simulation aus','display.simulate':'So tua als ob','display.preview':'OLED zum Gugga','display.dim_brightness':'Helligkeit gedimmt','display.off_after':'Ganz aus nach','display.off_help':'0 = normal bleibt s an; ohne Netz isch nach 15 s Feierabend.','display.layout':'Layout','display.standard':'Normal','display.compact':'Kompakt','display.large_clock':'Große Uhr','display.wake':'Bei Ereignis wieder aufwecka','display.invert':'Anzeige umdreha','display.rotate':'180° dreha','display.sim_help':'D Simulation nimmt genau dr gleiche 128×64-Framebuffer wie s echte OLED. Au ohne Display kasch Layout, Helligkeit, Dimma, Ausschalta und Ereignisreaktiona im Browser ausprobiera.','display.sim_switching':'I schalt d Simulation um …','display.sim_switch_error':'D Simulation hot sich ned umschalta lassa.','display.save_button':'Display speichera','display.test_button':'Display ausprobiera','display.hw_plus_sim':'Hardware gfunda · Simulation läuft zusätzlich','display.real_hw':'Echte Hardware gfunda','display.sim_no_hw':'Simulation läuft · koi Hardware gfunda','display.no_hw_sim_off':'Koi Hardware gfunda · Simulation aus','display.sim_active_title':'OLED-Simulation läuft','display.not_present_title':'OLED isch ned do','display.hardware_badge':'HARDWARE','display.simulation_badge':'SIMULATION','display.off':'AUS','display.dimmed':'GEDIMMT','display.on':'AN','display.off_overlay':'DISPLAY AUS',
  'network.signal':'Signal','network.rating':'Wie guat','network.very_good':'sauguat','network.good':'guat','network.fair':'goht no','network.weak':'a bissle mau','network.wifi_connected':'WLAN isch do','network.local_ap':'Lokals WLAN isch an','network.offline':'Grad koi Netz',
  'calendar.mon':'Mo','calendar.tue':'Di','calendar.wed':'Mi','calendar.thu':'Do','calendar.fri':'Fr','calendar.sat':'Sa','calendar.sun':'So','calendar.jan':'Jan','calendar.feb':'Feb','calendar.mar':'Mär','calendar.apr':'Apr','calendar.may':'Mai','calendar.jun':'Jun','calendar.jul':'Jul','calendar.aug':'Aug','calendar.sep':'Sep','calendar.oct':'Okt','calendar.nov':'Nov','calendar.dec':'Dez'
 }
};
const META={de:{label:'Deutsch',locale:'de-DE'},en:{label:'English',locale:'en-US'},swg:{label:'Schwäbisch',locale:'de-DE'}};
function code(){const wanted=localStorage.getItem('uic-lang')||'de';return EXTRA_I18N[wanted]?wanted:'de'}
function tr(key,vars){const map=EXTRA_I18N[code()]||EXTRA_I18N.de;let out=String(map[key]===undefined?(EXTRA_I18N.de[key]===undefined?key:EXTRA_I18N.de[key]):map[key]);if(vars)Object.keys(vars).forEach(k=>out=out.replaceAll('{'+k+'}',vars[k]));return out}
function locale(){return (META[code()]||META.de).locale}
function installLanguageOptions(){const select=$('languageSelect');if(!select)return;const expected=new Set();Object.entries(META).forEach(([language,meta])=>{expected.add(language);let option=select.querySelector('option[value="'+language+'"]');if(!option){option=document.createElement('option');option.value=language;select.appendChild(option)}setText(option,meta.label||language)});[...select.options].forEach(option=>{if(!expected.has(option.value))option.remove()});const current=code();if(document.activeElement!==select&&select.value!==current)select.value=current}
window.UicI18n={t:tr,current:code,locale:locale,languages:META};window.uicTr=tr;

const ACTIONS={addBtn:{running:'action.add.running',success:'action.add.success',error:'action.add.error'},undoBtn:{running:'action.delete.running',success:'action.delete.success',error:'action.delete.error'},ntpSaveBtn:{running:'action.ntp.running',success:'action.ntp.success',error:'action.ntp.error'},rtcSync:{running:'action.rtc.running',success:'action.rtc.success',error:'action.rtc.error'},displaySave:{running:'action.display_save.running',success:'action.display_save.success',error:'action.display_save.error'},displayTest:{running:'action.display_test.running',success:'action.display_test.success',error:'action.display_test.error'}};
const ENDPOINTS=[['/api/delete-last','undoBtn'],['/api/display-settings','displaySave'],['/api/display-test','displayTest'],['/api/rtc-sync','rtcSync'],['/api/ntp','ntpSaveBtn'],['/api/add','addBtn']];
function setText(el,value){if(el&&el.textContent!==value)el.textContent=value}
function nf(){return new Intl.NumberFormat(locale())}
function makeStorageNumberStable(id){const el=$(id);if(!el)return;el.classList.add('stableStorageNumber');if(!el.dataset.formatted)el.dataset.formatted=el.textContent||'-'}
function updateStableStorage(d){if(!d)return;const format=nf();[['devRecent',d.eventCount,d.ringCapacity],['devArchive',d.archiveCount,d.archiveCapacity],['devAutark',d.autarkCount,d.autarkCapacity]].forEach(v=>{const el=$(v[0]);if(!el)return;makeStorageNumberStable(v[0]);const next=format.format(Number(v[1]||0))+' / '+format.format(Number(v[2]||0));if(el.dataset.formatted!==next)el.dataset.formatted=next})}
function labelBefore(valueId,key){const value=$(valueId),label=value&&value.previousElementSibling;if(label)setText(label,tr(key))}
function meterLabel(id,key){const value=$(id+'Text'),head=value&&value.closest('.usageHead'),label=head&&head.querySelector('span');if(label)setText(label,tr(key))}
function exportCard(href,titleKey,purposeKey,buttonKey){const link=document.querySelector('#export a[href="'+href+'"]'),card=link&&link.closest('.card');if(!card)return;const heading=card.querySelector('h2');if(heading)setText(heading,'💾 '+tr(titleKey));let purpose=card.querySelector('.ringPurpose');if(!purpose){const old=card.querySelector('p');purpose=document.createElement('p');purpose.className='ringPurpose';if(old)old.replaceWith(purpose);else if(heading)heading.insertAdjacentElement('afterend',purpose)}const wanted=tr('storage.purpose')+' '+tr(purposeKey);if(purpose.textContent!==wanted){purpose.textContent='';const strong=document.createElement('strong');strong.textContent=tr('storage.purpose');purpose.appendChild(strong);purpose.appendChild(document.createTextNode(' '+tr(purposeKey)))}setText(link,tr(buttonKey))}
function exportMeta(id,count,capacity){const el=$(id);if(!el)return;const format=nf();setText(el,tr('storage.used')+format.format(Number(count||0))+' / '+format.format(Number(capacity||0)))}
function applyStorageI18n(status){labelBefore('devRecent','storage.normal_ring');labelBefore('devArchive','storage.long_ring');labelBefore('devAutark','storage.autark_ring');meterLabel('meterRecent','storage.normal_ring');meterLabel('meterArchive','storage.long_ring');meterLabel('meterAutark','storage.autark_ring');meterLabel('meterRam','dynamic.ram_usage');meterLabel('meterFlash','dynamic.program_storage');exportCard('/export.csv','storage.normal_ring','storage.normal_purpose','export.normal_csv');exportCard('/autark.csv','storage.autark_ring','storage.autark_purpose','export.autark_csv');exportCard('/archive.csv','storage.long_ring','storage.long_purpose','export.long_csv');if(status){exportMeta('recentExportMeta',status.eventCount,status.ringCapacity);exportMeta('archiveExportMeta',status.archiveCount,status.archiveCapacity);exportMeta('autarkExportMeta',status.autarkCount,status.autarkCapacity)}}
function installCounterIcons(){const add=$('addBtn'),del=$('undoBtn');if(add&&!add.querySelector('svg'))add.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 11V6.5a1.5 1.5 0 0 1 3 0V10"/><path d="M12 10V5.5a1.5 1.5 0 0 1 3 0V10"/><path d="M15 10V7a1.5 1.5 0 0 1 3 0v6.5"/><path d="M9 11 7.8 9.8a1.55 1.55 0 0 0-2.2 2.2l3.7 5.2A5 5 0 0 0 13.4 19H15a5 5 0 0 0 5-5v-2"/></svg>';if(del&&!del.querySelector('svg'))del.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18"/><path d="M8 6V4h8v2"/><path d="M19 6l-1 14H6L5 6"/><path d="M10 10v6M14 10v6"/></svg>'}
function actionKey(el){if(el.id)return el.id;if(el.matches('#export a[href="/export.csv"]'))return'export-normal';if(el.matches('#export a[href="/archive.csv"]'))return'export-archive';if(el.matches('#export a[href="/autark.csv"]'))return'export-autark';if(el.matches('[data-theme-choice]'))return'theme-'+el.dataset.themeChoice;return''}
function ensureActionUnit(el){if(!el||el.classList.contains('tab'))return null;let unit=el.parentElement&&el.parentElement.classList.contains('actionUnit')?el.parentElement:null;if(unit)return unit;const key=actionKey(el);if(!key)return null;unit=document.createElement('span');unit.className='actionUnit'+(el.classList.contains('countAction')?' center':'');el.parentNode.insertBefore(unit,el);unit.appendChild(el);const message=document.createElement('span');message.className='actionMessage';message.dataset.forAction=key;unit.appendChild(message);return unit}
function ensureActions(){document.querySelectorAll('#addBtn,#undoBtn,#ntpSaveBtn,#rtcSync,#displaySave,#displayTest,#export a.btn,[data-theme-choice]').forEach(ensureActionUnit)}
function messageEl(el){const unit=ensureActionUnit(el);return unit&&unit.querySelector('.actionMessage')}
function showMessage(el,text,kind){const m=messageEl(el);if(!m)return;setText(m,text);m.className='actionMessage show '+(kind||'');clearTimeout(m._hideTimer);m._hideTimer=setTimeout(()=>{m.className='actionMessage';m.textContent=''},5000)}
function setState(el,state){if(!el)return;el.classList.remove('actionRunning','actionSuccess','actionError');if(state)el.classList.add(state);clearTimeout(el._stateTimer);if(state&&state!=='actionRunning')el._stateTimer=setTimeout(()=>el.classList.remove(state),1400)}
function begin(id){const el=$(id),def=ACTIONS[id];if(el&&def){setState(el,'actionRunning');showMessage(el,tr(def.running),'')}}
function finish(id,ok){const el=$(id),def=ACTIONS[id];if(el&&def){setState(el,ok?'actionSuccess':'actionError');showMessage(el,tr(ok?def.success:def.error),ok?'ok':'bad')}}
function endpointAction(url){for(const pair of ENDPOINTS)if(url.indexOf(pair[0])>=0)return pair[1];return''}

function setSelector(selector,key){setText(document.querySelector(selector),tr(key))}
function setLabel(forId,key){setText(document.querySelector('label[for="'+forId+'"]'),tr(key))}
function setInputLabel(id,key){const input=$(id),label=input&&input.closest('label');if(!label)return;let node=[...label.childNodes].find(n=>n.nodeType===3&&n.textContent.trim());if(!node){node=document.createTextNode('');label.appendChild(node)}const value=tr(key);if(node.textContent.trim()!==value)node.textContent=' '+value}
function signalKey(rssi){return rssi>=-60?'network.very_good':rssi>=-67?'network.good':rssi>=-75?'network.fair':'network.weak'}
function applyAxes(){const dayKeys=['calendar.mon','calendar.tue','calendar.wed','calendar.thu','calendar.fri','calendar.sat','calendar.sun'],monthKeys=['calendar.jan','calendar.feb','calendar.mar','calendar.apr','calendar.may','calendar.jun','calendar.jul','calendar.aug','calendar.sep','calendar.oct','calendar.nov','calendar.dec'];const week=document.querySelector('#weekHeat table.heat');if(week)for(let i=1;i<week.rows.length&&i<=7;i++)if(week.rows[i].cells[0])setText(week.rows[i].cells[0],tr(dayKeys[i-1]));const mw=document.querySelector('#monthWeekHeat table.heat');if(mw)for(let i=1;i<mw.rows.length&&i<=12;i++)if(mw.rows[i].cells[0])setText(mw.rows[i].cells[0],tr(monthKeys[i-1]));const ym=document.querySelector('#yearMonthHeat table.heat');if(ym&&ym.rows[0])for(let i=1;i<ym.rows[0].cells.length&&i<=12;i++)setText(ym.rows[0].cells[i],tr(monthKeys[i-1]))}
function applyExtensionI18n(status){applyStorageI18n(status);setSelector('#deviceWifiSignalLabel','network.signal');setSelector('#deviceWifiRatingLabel','network.rating');if(status){const rssi=Number(status.rssi||0),quality=$('deviceWifiQuality');if(quality&&status.wifi&&rssi)setText(quality,tr(signalKey(rssi)));const wifiIcon=$('headWifiIcon');if(wifiIcon)wifiIcon.title=status.wifi?tr('network.wifi_connected'):((status.ip&&status.ip!=='-')?tr('network.local_ap'):tr('network.offline'));const displayIcon=$('headDisplay');if(displayIcon&&!status.displayPresent)displayIcon.title=status.displaySimulation?tr('display.sim_active_title'):tr('display.not_present_title')}setSelector('#displaySimulationRow .displaySimulationText b','display.simulation_title');setSelector('#displaySimulationRow .simToggle span:last-child','display.simulate');setSelector('#oledPreviewBlock .oledPreviewHead b','display.preview');setLabel('displayDimBrightness','display.dim_brightness');setLabel('displayOffAfter','display.off_after');setLabel('displayLayout','display.layout');setInputLabel('displayWakeOnEvent','display.wake');setInputLabel('displayInvert','display.invert');setInputLabel('displayRotation','display.rotate');const layout=$('displayLayout');if(layout){const keys=['display.standard','display.compact','display.large_clock'];[...layout.options].forEach((o,i)=>{if(keys[i])setText(o,tr(keys[i]))})}const hint=$('displayOffAfterRow')&&$('displayOffAfterRow').querySelector('.displayHint');if(hint)setText(hint,tr('display.off_help'));const advanced=$('displayCard')&&$('displayCard').querySelector('.displayAdvanced .infoHelp');if(advanced)setText(advanced,tr('display.sim_help'));if(status){const sim=$('displaySimulationState');if(sim){const key=status.displayPresent?(status.displaySimulation?'display.hw_plus_sim':'display.real_hw'):(status.displaySimulation?'display.sim_no_hw':'display.no_hw_sim_off');setText(sim,tr(key))}}const mode=$('oledModeBadge');if(mode)setText(mode,tr(mode.classList.contains('sim')?'display.simulation_badge':'display.hardware_badge'));const badge=$('oledStateBadge');if(badge)setText(badge,tr(badge.classList.contains('off')?'display.off':badge.classList.contains('dim')?'display.dimmed':'display.on'));setSelector('#oledOffOverlay','display.off_overlay');const save=$('displaySave'),test=$('displayTest');if(save&&!save.classList.contains('actionRunning')&&!save.classList.contains('actionSuccess')&&!save.classList.contains('actionError'))setText(save,tr('display.save_button'));if(test&&!test.classList.contains('actionRunning')&&!test.classList.contains('actionSuccess')&&!test.classList.contains('actionError'))setText(test,tr('display.test_button'));applyAxes()}

function fillHourGaps(){const host=$('hourBars');if(!host)return;const rows=[...host.querySelectorAll('.barrow')];if(rows.length<2)return;const byHour=new Map();rows.forEach(row=>{const hour=parseInt((row.children[0]&&row.children[0].textContent)||'',10);if(Number.isFinite(hour))byHour.set(hour,row)});const hours=[...byHour.keys()];if(hours.length<2)return;const first=Math.min(...hours),last=Math.max(...hours);let missing=false;for(let hour=first;hour<=last;hour++)if(!byHour.has(hour)){missing=true;break}if(!missing)return;const fragment=document.createDocumentFragment();for(let hour=first;hour<=last;hour++){if(byHour.has(hour)){fragment.appendChild(byHour.get(hour));continue}const row=document.createElement('div');row.className='barrow zeroHour';row.innerHTML='<span>'+String(hour).padStart(2,'0')+'-'+String((hour+1)%24).padStart(2,'0')+'</span><div class="barbg"><div class="bar" style="width:0%"></div></div><b>0</b>';fragment.appendChild(row)}host.replaceChildren(fragment)}
function prepareHeatmapCells(){document.querySelectorAll('.heat td').forEach(cell=>{if(!cell.hasAttribute('tabindex'))cell.tabIndex=0})}
function focusHeatCell(cell){if(!cell||!cell.matches('.heat td'))return;document.querySelectorAll('.heat td.heatFocus').forEach(c=>c.classList.remove('heatFocus'));cell.classList.add('heatFocus')}
document.addEventListener('focusin',event=>focusHeatCell(event.target),true);
document.addEventListener('click',event=>{const cell=event.target.closest('.heat td');if(cell){focusHeatCell(cell);cell.focus({preventScroll:true});return}const el=event.target.closest('button,.btn');if(!el||el.classList.contains('tab'))return;ensureActionUnit(el);if(el.matches('#export a.btn')){setState(el,'actionRunning');showMessage(el,tr('action.download.running'),'');setTimeout(()=>{setState(el,'actionSuccess');showMessage(el,tr('action.download.started'),'ok')},120);return}if(el.matches('[data-theme-choice]')){setState(el,'actionSuccess');showMessage(el,tr('action.theme.changed'),'ok');return}if(ACTIONS[el.id]){if(el.id==='ntpSaveBtn'){const input=$('ntpServer');if(input&&!input.value.trim()){setState(el,'actionError');showMessage(el,tr('action.ntp.enter'),'bad');return}}begin(el.id)}},true);

let lastStatus=null;
const originalFetch=window.fetch.bind(window);window.fetch=async function(){const args=arguments,url=String(args[0]||''),id=endpointAction(url);let response;try{response=await originalFetch.apply(null,args)}catch(error){if(id)finish(id,false);throw error}try{if(url.indexOf('/api/status')>=0&&response.ok)response.clone().json().then(d=>{lastStatus=d;setTimeout(()=>{updateStableStorage(d);applyExtensionI18n(d)},20)}).catch(()=>{});else if(url.indexOf('/api/display')>=0)setTimeout(()=>applyExtensionI18n(lastStatus),30);if(id)finish(id,response.ok)}catch(e){}return response};
let refreshQueued=false;function refresh(){if(refreshQueued)return;refreshQueued=true;setTimeout(()=>{refreshQueued=false;installLanguageOptions();ensureActions();installCounterIcons();fillHourGaps();prepareHeatmapCells();applyExtensionI18n(lastStatus)},0)}
function observeDynamicArea(id,callback){const el=$(id);if(!el)return;new MutationObserver(()=>setTimeout(callback,0)).observe(el,{childList:true})}
['devRecent','devArchive','devAutark'].forEach(makeStorageNumberStable);installLanguageOptions();refresh();setTimeout(refresh,80);setTimeout(refresh,350);setTimeout(refresh,900);observeDynamicArea('hourBars',fillHourGaps);['weekHeat','monthWeekHeat','yearMonthHeat'].forEach(id=>observeDynamicArea(id,()=>{prepareHeatmapCells();applyAxes()}));const language=$('languageSelect');if(language)language.addEventListener('change',()=>{setTimeout(refresh,30);setTimeout(refresh,180);setTimeout(refresh,500)});
})();
</script>
)HTML";
