#!/usr/bin/env python3
"""Bundle the readable web sources and generate a gzip-compressed PROGMEM header.

Uses Python's standard library only. No JS/CSS minifier is required: bundling removes
extra HTTP requests, while gzip provides most of the deployment-size win without
making the source files unreadable.
"""
from __future__ import annotations

import gzip
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "ui-src"
OUT = ROOT / "web_assets.h"

html = (SRC / "index.html").read_text(encoding="utf-8")
css = (SRC / "app.css").read_text(encoding="utf-8")
js = (SRC / "app.js").read_text(encoding="utf-8")

if "/*__APP_CSS__*/" not in html or "/*__APP_JS__*/" not in html:
    raise SystemExit("Bundle placeholders are missing from ui-src/index.html")

bundle = html.replace("/*__APP_CSS__*/", css).replace("/*__APP_JS__*/", js).encode("utf-8")
compressed = gzip.compress(bundle, compresslevel=9, mtime=0)
etag_token = hashlib.sha256(compressed).hexdigest()[:16]
etag = '"' + etag_token + '"'

lines = []
for offset in range(0, len(compressed), 16):
    chunk = compressed[offset:offset + 16]
    lines.append("  " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")

header = f"""#pragma once

#include <Arduino.h>

// Generated by tools/build_web.py. Edit ui-src/*, then run the script again.
static const uint8_t INDEX_HTML_GZ[] PROGMEM = {{
{chr(10).join(lines)}
}};
static constexpr size_t INDEX_HTML_GZ_LEN = sizeof(INDEX_HTML_GZ);
static constexpr char WEB_ASSET_ETAG[] = "\\\"{etag_token}\\\"";
"""
with OUT.open("w", encoding="utf-8", newline="\n") as handle:
    handle.write(header)

print(f"Uncompressed bundle: {len(bundle)} bytes")
print(f"Gzip asset:          {len(compressed)} bytes")
print(f"ETag:                {etag}")
print(f"Generated:           {OUT}")
